import { Data } from "./data";

export const MUNICIPIOS: Data[] = [
    { id: 1, value: 'Libertador', value2: '', value3: '' },
    { id: 2, value: 'Alto Orinoco', value2: '', value3: '' },
    { id: 3, value: 'Atabapo', value2: '', value3: '' },
    { id: 4, value: 'Atures', value2: '', value3: '' },
    { id: 5, value: 'Autana', value2: '', value3: '' },
    { id: 6, value: 'Manapiare', value2: '', value3: '' },
    { id: 7, value: 'Maroa', value2: '', value3: '' },
    { id: 8, value: 'Río Negro', value2: '', value3: '' },
    { id: 9, value: 'Anaco', value2: '', value3: '' },
    { id: 10, value: 'Aragua', value2: '', value3: '' },
    { id: 11, value: 'Diego Bautista Urbaneja', value2: '', value3: '' },
    { id: 12, value: 'Fernando Peñalver', value2: '', value3: '' },
    { id: 13, value: 'Francisco del Carmen Carvajal', value2: '', value3: '' },
    { id: 14, value: 'Francisco de Miranda', value2: '', value3: '' },
    { id: 15, value: 'Guanta', value2: '', value3: '' },
    { id: 16, value: 'Independencia', value2: '', value3: '' },
    { id: 17, value: 'José Gregorio Monagas', value2: '', value3: '' },
    { id: 18, value: 'Juan Antonio Sotillo', value2: '', value3: '' },
    { id: 19, value: 'Juan Manuel Cajigal', value2: '', value3: '' },
    { id: 20, value: 'Libertad', value2: '', value3: '' },
    { id: 21, value: 'Manuel Ezequiel Bruzual', value2: '', value3: '' },
    { id: 22, value: 'Pedro María Freites', value2: '', value3: '' },
    { id: 23, value: 'Píritu', value2: '', value3: '' },
    { id: 24, value: 'San José de Guanipa', value2: '', value3: '' },
    { id: 25, value: 'San Juan de Capistrano', value2: '', value3: '' },
    { id: 26, value: 'Santa Ana', value2: '', value3: '' },
    { id: 27, value: 'Simón Bolívar', value2: '', value3: '' },
    { id: 28, value: 'Simón Rodríguez', value2: '', value3: '' },
    { id: 29, value: 'General Sir Arthur McGregor', value2: '', value3: '' },
    { id: 30, value: 'Achaguas', value2: '', value3: '' },
    { id: 31, value: 'Biruaca', value2: '', value3: '' },
    { id: 32, value: 'Muñoz', value2: '', value3: '' },
    { id: 33, value: 'Pedro Camejo', value2: '', value3: '' },
    { id: 34, value: 'San Fernando', value2: '', value3: '' },
    { id: 35, value: 'Páez', value2: '', value3: '' },
    { id: 36, value: 'Rómulo Gallegos', value2: '', value3: '' },
    { id: 37, value: 'Bolívar', value2: '', value3: '' },
    { id: 38, value: 'Camatagua', value2: '', value3: '' },
    { id: 39, value: 'Francisco Linares Alcántara', value2: '', value3: '' },
    { id: 40, value: 'Girardot', value2: '', value3: '' },
    { id: 41, value: 'José Ángel Lamas', value2: '', value3: '' },
    { id: 42, value: 'José Félix Ribas', value2: '', value3: '' },
    { id: 43, value: 'José Rafael Revenga', value2: '', value3: '' },
    { id: 44, value: 'Mario Briceño Iragorry', value2: '', value3: '' },
    { id: 45, value: 'Ocumare de la Costa de Oro', value2: '', value3: '' },
    { id: 46, value: 'San Casimiro', value2: '', value3: '' },
    { id: 47, value: 'San Sebastián', value2: '', value3: '' },
    { id: 48, value: 'Santiago Mariño', value2: '', value3: '' },
    { id: 49, value: 'Santos Michelena', value2: '', value3: '' },
    { id: 50, value: 'Sucre', value2: '', value3: '' },
    { id: 51, value: 'Tovar', value2: '', value3: '' },
    { id: 52, value: 'Urdaneta', value2: '', value3: '' },
    { id: 53, value: 'Zamora', value2: '', value3: '' },
    { id: 54, value: 'Alberto Arvelo Torrealba', value2: '', value3: '' },
    { id: 55, value: 'Andrés Eloy Blanco', value2: '', value3: '' },
    { id: 56, value: 'Antonio José de Sucre', value2: '', value3: '' },
    { id: 57, value: 'Arismendi', value2: '', value3: '' },
    { id: 58, value: 'Barinas', value2: '', value3: '' },
    { id: 59, value: 'Cruz Paredes', value2: '', value3: '' },
    { id: 60, value: 'Ezequiel Zamora', value2: '', value3: '' },
    { id: 61, value: 'Obispos', value2: '', value3: '' },
    { id: 62, value: 'Pedraza', value2: '', value3: '' },
    { id: 63, value: 'Rojas', value2: '', value3: '' },
    { id: 64, value: 'Sosa', value2: '', value3: '' },
    { id: 65, value: 'Caroní', value2: '', value3: '' },
    { id: 66, value: 'Cedeño', value2: '', value3: '' },
    { id: 67, value: 'El Callao', value2: '', value3: '' },
    { id: 68, value: 'Gran Sabana', value2: '', value3: '' },
    { id: 69, value: 'Heres', value2: '', value3: '' },
    { id: 70, value: 'Padre Pedro Chien', value2: '', value3: '' },
    { id: 71, value: 'Piar', value2: '', value3: '' },
    { id: 72, value: 'Angostura (Raúl Leoni)', value2: '', value3: '' },
    { id: 73, value: 'Roscio', value2: '', value3: '' },
    { id: 74, value: 'Sifontes', value2: '', value3: '' },
    { id: 75, value: 'Bejuma', value2: '', value3: '' },
    { id: 76, value: 'Carlos Arvelo', value2: '', value3: '' },
    { id: 77, value: 'Diego Ibarra', value2: '', value3: '' },
    { id: 78, value: 'Guacara', value2: '', value3: '' },
    { id: 79, value: 'Juan José Mora', value2: '', value3: '' },
    { id: 80, value: 'Los Guayos', value2: '', value3: '' },
    { id: 81, value: 'Miranda', value2: '', value3: '' },
    { id: 82, value: 'Montalbán', value2: '', value3: '' },
    { id: 83, value: 'Naguanagua', value2: '', value3: '' },
    { id: 84, value: 'Puerto Cabello', value2: '', value3: '' },
    { id: 85, value: 'San Diego', value2: '', value3: '' },
    { id: 86, value: 'San Joaquín', value2: '', value3: '' },
    { id: 87, value: 'Valencia', value2: '', value3: '' },
    { id: 88, value: 'Anzoátegui', value2: '', value3: '' },
    { id: 89, value: 'Pao de San Juan Bautista', value2: '', value3: '' },
    { id: 90, value: 'Tinaquillo', value2: '', value3: '' },
    { id: 91, value: 'Lima Blanco', value2: '', value3: '' },
    { id: 92, value: 'Ricaurte', value2: '', value3: '' },
    { id: 93, value: 'Ezequiel Zamora (Cojedes)', value2: '', value3: '' },
    { id: 94, value: 'Tinaco', value2: '', value3: '' },
    { id: 95, value: 'Antonio Díaz', value2: '', value3: '' },
    { id: 96, value: 'Casacoima', value2: '', value3: '' },
    { id: 97, value: 'Pedernales', value2: '', value3: '' },
    { id: 98, value: 'Tucupita', value2: '', value3: '' },
    { id: 99, value: 'Acosta', value2: '', value3: '' },
    { id: 100, value: 'Buchivacoa', value2: '', value3: '' },
    { id: 101, value: 'Cacique Manaure', value2: '', value3: '' },
    { id: 102, value: 'Carirubana', value2: '', value3: '' },
    { id: 103, value: 'Colina', value2: '', value3: '' },
    { id: 104, value: 'Dabajuro', value2: '', value3: '' },
    { id: 105, value: 'Democracia', value2: '', value3: '' },
    { id: 106, value: 'Falcón', value2: '', value3: '' },
    { id: 107, value: 'Federación', value2: '', value3: '' },
    { id: 108, value: 'Jacura', value2: '', value3: '' },
    { id: 109, value: 'Los Taques', value2: '', value3: '' },
    { id: 110, value: 'Mauroa', value2: '', value3: '' },
    { id: 111, value: 'Monseñor Iturriza', value2: '', value3: '' },
    { id: 112, value: 'Palmasola', value2: '', value3: '' },
    { id: 113, value: 'Petit', value2: '', value3: '' },
    { id: 114, value: 'San Francisco', value2: '', value3: '' },
    { id: 115, value: 'José Laurencio Silva', value2: '', value3: '' },
    { id: 116, value: 'Tocópero', value2: '', value3: '' },
    { id: 117, value: 'Unión', value2: '', value3: '' },
    { id: 118, value: 'Urumaco', value2: '', value3: '' },
    { id: 119, value: 'Camaguán', value2: '', value3: '' },
    { id: 120, value: 'Chaguaramas', value2: '', value3: '' },
    { id: 121, value: 'El Socorro', value2: '', value3: '' },
    { id: 122, value: 'José Tadeo Monagas', value2: '', value3: '' },
    { id: 123, value: 'Juan Germán Roscio', value2: '', value3: '' },
    { id: 124, value: 'Julián Mellado', value2: '', value3: '' },
    { id: 125, value: 'Las Mercedes', value2: '', value3: '' },
    { id: 126, value: 'Leonardo Infante', value2: '', value3: '' },
    { id: 127, value: 'Ortiz', value2: '', value3: '' },
    { id: 128, value: 'Pedro Zaraza', value2: '', value3: '' },
    { id: 129, value: 'San Jerónimo de Guayabal', value2: '', value3: '' },
    { id: 130, value: 'San José de Guaribe', value2: '', value3: '' },
    { id: 131, value: 'Santa María de Ipire', value2: '', value3: '' },
    { id: 132, value: 'Crespo', value2: '', value3: '' },
    { id: 133, value: 'Iribarren', value2: '', value3: '' },
    { id: 134, value: 'Jiménez', value2: '', value3: '' },
    { id: 135, value: 'Morán', value2: '', value3: '' },
    { id: 136, value: 'Palavecino', value2: '', value3: '' },
    { id: 137, value: 'Simón Planas', value2: '', value3: '' },
    { id: 138, value: 'Torres', value2: '', value3: '' },
    { id: 139, value: 'Alberto Adriani', value2: '', value3: '' },
    { id: 140, value: 'Andrés Bello', value2: '', value3: '' },
    { id: 141, value: 'Antonio Pinto Salinas', value2: '', value3: '' },
    { id: 142, value: 'Aricagua', value2: '', value3: '' },
    { id: 143, value: 'Arzobispo Chacón', value2: '', value3: '' },
    { id: 144, value: 'Campo Elías', value2: '', value3: '' },
    { id: 145, value: 'Caracciolo Parra Olmedo', value2: '', value3: '' },
    { id: 146, value: 'Cardenal Quintero', value2: '', value3: '' },
    { id: 147, value: 'Guaraque', value2: '', value3: '' },
    { id: 148, value: 'Julio César Salas', value2: '', value3: '' },
    { id: 149, value: 'Justo Briceño', value2: '', value3: '' },
    { id: 150, value: 'Obispo Ramos de Lora', value2: '', value3: '' },
    { id: 151, value: 'Padre Noguera', value2: '', value3: '' },
    { id: 152, value: 'Pueblo Llano', value2: '', value3: '' },
    { id: 153, value: 'Rangel', value2: '', value3: '' },
    { id: 154, value: 'Rivas Dávila', value2: '', value3: '' },
    { id: 155, value: 'Santos Marquina', value2: '', value3: '' },
    { id: 156, value: 'Tulio Febres Cordero', value2: '', value3: '' },
    { id: 157, value: 'Zea', value2: '', value3: '' },
    { id: 158, value: 'Acevedo', value2: '', value3: '' },
    { id: 159, value: 'Baruta', value2: '', value3: '' },
    { id: 160, value: 'Brión', value2: '', value3: '' },
    { id: 161, value: 'Buroz', value2: '', value3: '' },
    { id: 162, value: 'Carrizal', value2: '', value3: '' },
    { id: 163, value: 'Chacao', value2: '', value3: '' },
    { id: 164, value: 'Cristóbal Rojas', value2: '', value3: '' },
    { id: 165, value: 'El Hatillo', value2: '', value3: '' },
    { id: 166, value: 'Guaicaipuro', value2: '', value3: '' },
    { id: 167, value: 'Lander', value2: '', value3: '' },
    { id: 168, value: 'Los Salias', value2: '', value3: '' },
    { id: 169, value: 'Paz Castillo', value2: '', value3: '' },
    { id: 170, value: 'Pedro Gual', value2: '', value3: '' },
    { id: 171, value: 'Plaza', value2: '', value3: '' },
    { id: 172, value: 'Aguasay', value2: '', value3: '' },
    { id: 173, value: 'Caripe', value2: '', value3: '' },
    { id: 174, value: 'Maturín', value2: '', value3: '' },
    { id: 175, value: 'Punceres', value2: '', value3: '' },
    { id: 176, value: 'Santa Bárbara', value2: '', value3: '' },
    { id: 177, value: 'Sotillo', value2: '', value3: '' },
    { id: 178, value: 'Uracoa', value2: '', value3: '' },
    { id: 179, value: 'Antolín del Campo', value2: '', value3: '' },
    { id: 180, value: 'Díaz', value2: '', value3: '' },
    { id: 181, value: 'García', value2: '', value3: '' },
    { id: 182, value: 'Gómez', value2: '', value3: '' },
    { id: 183, value: 'Macanao', value2: '', value3: '' },
    { id: 184, value: 'Maneiro', value2: '', value3: '' },
    { id: 185, value: 'Marcano', value2: '', value3: '' },
    { id: 186, value: 'Mariño', value2: '', value3: '' },
    { id: 187, value: 'Tubores', value2: '', value3: '' },
    { id: 188, value: 'Villalba', value2: '', value3: '' },
    { id: 189, value: 'Agua Blanca', value2: '', value3: '' },
    { id: 190, value: 'Araure', value2: '', value3: '' },
    { id: 191, value: 'Esteller', value2: '', value3: '' },
    { id: 192, value: 'Guanare', value2: '', value3: '' },
    { id: 193, value: 'Guanarito', value2: '', value3: '' },
    { id: 194, value: 'Monseñor José Vicente de Unda', value2: '', value3: '' },
    { id: 195, value: 'Ospino', value2: '', value3: '' },
    { id: 196, value: 'Papelón', value2: '', value3: '' },
    { id: 197, value: 'San Genaro de Boconoíto', value2: '', value3: '' },
    { id: 198, value: 'San Rafael de Onoto', value2: '', value3: '' },
    { id: 199, value: 'Santa Rosalía', value2: '', value3: '' },
    { id: 200, value: 'Turén', value2: '', value3: '' },
    { id: 201, value: 'Andrés Mata', value2: '', value3: '' },
    { id: 202, value: 'Benítez', value2: '', value3: '' },
    { id: 203, value: 'Bermúdez', value2: '', value3: '' },
    { id: 204, value: 'Cajigal', value2: '', value3: '' },
    { id: 205, value: 'Cruz Salmerón Acosta', value2: '', value3: '' },
    { id: 206, value: 'Mejía', value2: '', value3: '' },
    { id: 207, value: 'Montes', value2: '', value3: '' },
    { id: 208, value: 'Ribero', value2: '', value3: '' },
    { id: 209, value: 'Valdez', value2: '', value3: '' },
    { id: 210, value: 'Antonio Rómulo Costa', value2: '', value3: '' },
    { id: 211, value: 'Ayacucho', value2: '', value3: '' },
    { id: 212, value: 'Cárdenas', value2: '', value3: '' },
    { id: 213, value: 'Córdoba', value2: '', value3: '' },
    { id: 214, value: 'Fernández Feo', value2: '', value3: '' },
    { id: 215, value: 'García de Hevia', value2: '', value3: '' },
    { id: 216, value: 'Guásimos', value2: '', value3: '' },
    { id: 217, value: 'Jáuregui', value2: '', value3: '' },
    { id: 218, value: 'José María Vargas', value2: '', value3: '' },
    { id: 219, value: 'Junín', value2: '', value3: '' },
    { id: 220, value: 'Lobatera', value2: '', value3: '' },
    { id: 221, value: 'Michelena', value2: '', value3: '' },
    { id: 222, value: 'Panamericano', value2: '', value3: '' },
    { id: 223, value: 'Pedro María Ureña', value2: '', value3: '' },
    { id: 224, value: 'Rafael Urdaneta', value2: '', value3: '' },
    { id: 225, value: 'Samuel Dario Maldonado', value2: '', value3: '' },
    { id: 226, value: 'San Cristóbal', value2: '', value3: '' },
    { id: 227, value: 'San Judas Tadeo', value2: '', value3: '' },
    { id: 228, value: 'Seboruco', value2: '', value3: '' },
    { id: 229, value: 'Torbes', value2: '', value3: '' },
    { id: 230, value: 'Uribante', value2: '', value3: '' },
    { id: 231, value: 'Boconó', value2: '', value3: '' },
    { id: 232, value: 'Candelaria', value2: '', value3: '' },
    { id: 233, value: 'Carache', value2: '', value3: '' },
    { id: 234, value: 'Escuque', value2: '', value3: '' },
    { id: 235, value: 'José Felipe Márquez Cañizales', value2: '', value3: '' },
    { id: 236, value: 'Juan Vicente Campos Elías', value2: '', value3: '' },
    { id: 237, value: 'La Ceiba', value2: '', value3: '' },
    { id: 238, value: 'Monte Carmelo', value2: '', value3: '' },
    { id: 239, value: 'Motatán', value2: '', value3: '' },
    { id: 240, value: 'Pampán', value2: '', value3: '' },
    { id: 241, value: 'Pampanito', value2: '', value3: '' },
    { id: 242, value: 'Rafael Rangel', value2: '', value3: '' },
    { id: 243, value: 'San Rafael De Carvajal', value2: '', value3: '' },
    { id: 244, value: 'Trujillo', value2: '', value3: '' },
    { id: 245, value: 'Valera', value2: '', value3: '' },
    { id: 246, value: 'Vargas', value2: '', value3: '' },
    { id: 247, value: 'Arístides Bastidas', value2: '', value3: '' },
    { id: 248, value: 'Bruzual', value2: '', value3: '' },
    { id: 249, value: 'Cocorote', value2: '', value3: '' },
    { id: 250, value: 'José Antonio Páez', value2: '', value3: '' },
    { id: 251, value: 'José Joaquín Veroes', value2: '', value3: '' },
    { id: 252, value: 'La Trinidad', value2: '', value3: '' },
    { id: 253, value: 'Manuel Monge', value2: '', value3: '' },
    { id: 254, value: 'Nirgua', value2: '', value3: '' },
    { id: 255, value: 'Peña', value2: '', value3: '' },
    { id: 256, value: 'San Felipe', value2: '', value3: '' },
    { id: 257, value: 'Urachiche', value2: '', value3: '' },
    { id: 258, value: 'Almirante Padilla', value2: '', value3: '' },
    { id: 259, value: 'Baralt', value2: '', value3: '' },
    { id: 260, value: 'Cabimas', value2: '', value3: '' },
    { id: 261, value: 'Catatumbo', value2: '', value3: '' },
    { id: 262, value: 'Colón', value2: '', value3: '' },
    { id: 263, value: 'Francisco Javier Pulgar', value2: '', value3: '' },
    { id: 264, value: 'Jesús Enrique Lossada', value2: '', value3: '' },
    { id: 265, value: 'Jesús María Semprún', value2: '', value3: '' },
    { id: 266, value: 'La Cañada De Urdaneta', value2: '', value3: '' },
    { id: 267, value: 'Lagunillas', value2: '', value3: '' },
    { id: 268, value: 'Machiques De Perijá', value2: '', value3: '' },
    { id: 269, value: 'Mara', value2: '', value3: '' },
    { id: 270, value: 'Maracaibo', value2: '', value3: '' },
    { id: 271, value: 'Guajira', value2: '', value3: '' },
    { id: 272, value: 'Rosario De Perijá', value2: '', value3: '' },
    { id: 273, value: 'Santa Rita', value2: '', value3: '' },
    { id: 274, value: 'Valmore Rodríguez', value2: '', value3: '' }
];