import { Data } from "./data";

export const PAISES: Data[] = [
    { id: 1, value: 'Afganistán', value2: 'Afghanistan', value3: 'AF' },
    { id: 2, value: 'Albania', value2: 'Albania', value3: 'AL' },
    { id: 3, value: 'Alemania', value2: 'Germany', value3: 'DE' },
    { id: 4, value: 'Andorra', value2: 'Andorra', value3: 'AD' },
    { id: 5, value: 'Angola', value2: 'Angola', value3: 'AO' },
    { id: 6, value: 'Anguila', value2: 'Anguilla', value3: 'AI' },
    { id: 7, value: 'Antártida', value2: 'Antarctica', value3: 'AQ' },
    { id: 8, value: 'Antigua y Barbuda', value2: 'Antigua and Barbuda', value3: 'AG' },
    { id: 9, value: 'Arabia Saudita', value2: 'Saudi Arabia', value3: 'SA' },
    { id: 10, value: 'Argelia', value2: 'Algeria', value3: 'DZ' },
    { id: 11, value: 'Argentina', value2: 'Argentina', value3: 'AR' },
    { id: 12, value: 'Armenia', value2: 'Armenia', value3: 'AM' },
    { id: 13, value: 'Aruba', value2: 'Aruba', value3: 'AW' },
    { id: 14, value: 'Australia', value2: 'Australia', value3: 'AU' },
    { id: 15, value: 'Austria', value2: 'Austria', value3: 'AT' },
    { id: 16, value: 'Azerbaiyán', value2: 'Azerbaijan', value3: 'AZ' },
    { id: 17, value: 'Bélgica', value2: 'Belgium', value3: 'BE' },
    { id: 18, value: 'Bahamas', value2: 'Bahamas', value3: 'BS' },
    { id: 19, value: 'Bahrein', value2: 'Bahrain', value3: 'BH' },
    { id: 20, value: 'Bangladesh', value2: 'Bangladesh', value3: 'BD' },
    { id: 21, value: 'Barbados', value2: 'Barbados', value3: 'BB' },
    { id: 22, value: 'Belice', value2: 'Belize', value3: 'BZ' },
    { id: 23, value: 'Benín', value2: 'Benin', value3: 'BJ' },
    { id: 24, value: 'Bhután', value2: 'Bhutan', value3: 'BT' },
    { id: 25, value: 'Bielorrusia', value2: 'Belarus', value3: 'BY' },
    { id: 26, value: 'Birmania', value2: 'Myanmar', value3: 'MM' },
    { id: 27, value: 'Bolivia', value2: 'Bolivia', value3: 'BO' },
    { id: 28, value: 'Bosnia y Herzegovina', value2: 'Bosnia and Herzegovina', value3: 'BA' },
    { id: 29, value: 'Botsuana', value2: 'Botswana', value3: 'BW' },
    { id: 30, value: 'Brasil', value2: 'Brazil', value3: 'BR' },
    { id: 31, value: 'Brunéi', value2: 'Brunei', value3: 'BN' },
    { id: 32, value: 'Bulgaria', value2: 'Bulgaria', value3: 'BG' },
    { id: 33, value: 'Burkina Faso', value2: 'Burkina Faso', value3: 'BF' },
    { id: 34, value: 'Burundi', value2: 'Burundi', value3: 'BI' },
    { id: 35, value: 'Cabo Verde', value2: 'Cape Verde', value3: 'CV' },
    { id: 36, value: 'Camboya', value2: 'Cambodia', value3: 'KH' },
    { id: 37, value: 'Camerún', value2: 'Cameroon', value3: 'CM' },
    { id: 38, value: 'Canadá', value2: 'Canada', value3: 'CA' },
    { id: 39, value: 'Chad', value2: 'Chad', value3: 'TD' },
    { id: 40, value: 'Chile', value2: 'Chile', value3: 'CL' },
    { id: 41, value: 'China', value2: 'China', value3: 'CN' },
    { id: 42, value: 'Chipre', value2: 'Cyprus', value3: 'CY' },
    { id: 43, value: 'Ciudad del Vaticano', value2: 'Vatican City State', value3: 'VA' },
    { id: 44, value: 'Colombia', value2: 'Colombia', value3: 'CO' },
    { id: 45, value: 'Comoras', value2: 'Comoros', value3: 'KM' },
    { id: 46, value: 'República del Congo', value2: 'Republic of the Congo', value3: 'CG' },
    { id: 47, value: 'República Democrática del Congo', value2: 'Democratic Republic of the Congo', value3: 'CD' },
    { id: 48, value: 'Corea del Norte', value2: 'North Korea', value3: 'KP' },
    { id: 49, value: 'Corea del Sur', value2: 'South Korea', value3: 'KR' },
    { id: 50, value: 'Costa de Marfil', value2: 'Ivory Coast', value3: 'CI' },
    { id: 51, value: 'Costa Rica', value2: 'Costa Rica', value3: 'CR' },
    { id: 52, value: 'Croacia', value2: 'Croatia', value3: 'HR' },
    { id: 53, value: 'Cuba', value2: 'Cuba', value3: 'CU' },
    { id: 54, value: 'Curazao', value2: 'Curaçao', value3: 'CW' },
    { id: 55, value: 'Dinamarca', value2: 'Denmark', value3: 'DK' },
    { id: 56, value: 'Dominica', value2: 'Dominica', value3: 'DM' },
    { id: 57, value: 'Ecuador', value2: 'Ecuador', value3: 'EC' },
    { id: 58, value: 'Egipto', value2: 'Egypt', value3: 'EG' },
    { id: 59, value: 'El Salvador', value2: 'El Salvador', value3: 'SV' },
    { id: 60, value: 'Emiratos Árabes Unidos', value2: 'United Arab Emirates', value3: 'AE' },
    { id: 61, value: 'Eritrea', value2: 'Eritrea', value3: 'ER' },
    { id: 62, value: 'Eslovaquia', value2: 'Slovakia', value3: 'SK' },
    { id: 63, value: 'Eslovenia', value2: 'Slovenia', value3: 'SI' },
    { id: 64, value: 'España', value2: 'Spain', value3: 'ES' },
    { id: 65, value: 'Estados Unidos de América', value2: 'United States of America', value3: 'US' },
    { id: 66, value: 'Estonia', value2: 'Estonia', value3: 'EE' },
    { id: 67, value: 'Etiopía', value2: 'Ethiopia', value3: 'ET' },
    { id: 68, value: 'Filipinas', value2: 'Philippines', value3: 'PH' },
    { id: 69, value: 'Finlandia', value2: 'Finland', value3: 'FI' },
    { id: 70, value: 'Fiyi', value2: 'Fiji', value3: 'FJ' },
    { id: 71, value: 'Francia', value2: 'France', value3: 'FR' },
    { id: 72, value: 'Gabón', value2: 'Gabon', value3: 'GA' },
    { id: 73, value: 'Gambia', value2: 'Gambia', value3: 'GM' },
    { id: 74, value: 'Georgia', value2: 'Georgia', value3: 'GE' },
    { id: 75, value: 'Ghana', value2: 'Ghana', value3: 'GH' },
    { id: 76, value: 'Gibraltar', value2: 'Gibraltar', value3: 'GI' },
    { id: 77, value: 'Granada', value2: 'Grenada', value3: 'GD' },
    { id: 78, value: 'Grecia', value2: 'Greece', value3: 'GR' },
    { id: 79, value: 'Groenlandia', value2: 'Greenland', value3: 'GL' },
    { id: 80, value: 'Guadalupe', value2: 'Guadeloupe', value3: 'GP' },
    { id: 81, value: 'Guam', value2: 'Guam', value3: 'GU' },
    { id: 82, value: 'Guatemala', value2: 'Guatemala', value3: 'GT' },
    { id: 83, value: 'Guayana Francesa', value2: 'French Guiana', value3: 'GF' },
    { id: 84, value: 'Guernsey', value2: 'Guernsey', value3: 'GG' },
    { id: 85, value: 'Guinea', value2: 'Guinea', value3: 'GN' },
    { id: 86, value: 'Guinea Ecuatorial', value2: 'Equatorial Guinea', value3: 'GQ' },
    { id: 87, value: 'Guinea-Bissau', value2: 'Guinea-Bissau', value3: 'GW' },
    { id: 88, value: 'Guyana', value2: 'Guyana', value3: 'GY' },
    { id: 89, value: 'Haití', value2: 'Haiti', value3: 'HT' },
    { id: 90, value: 'Honduras', value2: 'Honduras', value3: 'HN' },
    { id: 91, value: 'Hong kong', value2: 'Hong Kong', value3: 'HK' },
    { id: 92, value: 'Hungría', value2: 'Hungary', value3: 'HU' },
    { id: 93, value: 'India', value2: 'India', value3: 'IN' },
    { id: 94, value: 'Indonesia', value2: 'Indonesia', value3: 'ID' },
    { id: 95, value: 'Irán', value2: 'Iran', value3: 'IR' },
    { id: 96, value: 'Irak', value2: 'Iraq', value3: 'IQ' },
    { id: 97, value: 'Irlanda', value2: 'Ireland', value3: 'IE' },
    { id: 98, value: 'Isla Bouvet', value2: 'Bouvet Island', value3: 'BV' },
    { id: 99, value: 'Isla de Man', value2: 'Isle of Man', value3: 'IM' },
    { id: 100, value: 'Isla de Navidad', value2: 'Christmas Island', value3: 'CX' },
    { id: 101, value: 'Isla Norfolk', value2: 'Norfolk Island', value3: 'NF' },
    { id: 102, value: 'Islandia', value2: 'Iceland', value3: 'IS' },
    { id: 103, value: 'Islas Bermudas', value2: 'Bermuda Islands', value3: 'BM' },
    { id: 104, value: 'Islas Caimán', value2: 'Cayman Islands', value3: 'KY' },
    { id: 105, value: 'Islas Cocos (Keeling)', value2: 'Cocos (Keeling) Islands', value3: 'CC' },
    { id: 106, value: 'Islas Cook', value2: 'Cook Islands', value3: 'CK' },
    { id: 107, value: 'Islas de Åland', value2: 'Åland Islands', value3: 'AX' },
    { id: 108, value: 'Islas Feroe', value2: 'Faroe Islands', value3: 'FO' },
    { id: 109, value: 'Islas Georgias del Sur y Sandwich del Sur', value2: 'South Georgia and the South Sandwich Islands', value3: 'GS' },
    { id: 110, value: 'Islas Heard y McDonald', value2: 'Heard Island and McDonald Islands', value3: 'HM' },
    { id: 111, value: 'Islas Maldivas', value2: 'Maldives', value3: 'MV' },
    { id: 112, value: 'Islas Malvinas', value2: 'Falkland Islands (Malvinas)', value3: 'FK' },
    { id: 113, value: 'Islas Marianas del Norte', value2: 'Northern Mariana Islands', value3: 'MP' },
    { id: 114, value: 'Islas Marshall', value2: 'Marshall Islands', value3: 'MH' },
    { id: 115, value: 'Islas Pitcairn', value2: 'Pitcairn Islands', value3: 'PN' },
    { id: 116, value: 'Islas Salomón', value2: 'Solomon Islands', value3: 'SB' },
    { id: 117, value: 'Islas Turcas y Caicos', value2: 'Turks and Caicos Islands', value3: 'TC' },
    { id: 118, value: 'Islas Ultramarinas Menores de Estados Unidos', value2: 'United States Minor Outlying Islands', value3: 'UM' },
    { id: 119, value: 'Islas Vírgenes Británicas', value2: 'Virgin Islands', value3: 'VG' },
    { id: 120, value: 'Islas Vírgenes de los Estados Unidos', value2: 'United States Virgin Islands', value3: 'VI' },
    { id: 121, value: 'Israel', value2: 'Israel', value3: 'IL' },
    { id: 122, value: 'Italia', value2: 'Italy', value3: 'IT' },
    { id: 123, value: 'Jamaica', value2: 'Jamaica', value3: 'JM' },
    { id: 124, value: 'Japón', value2: 'Japan', value3: 'JP' },
    { id: 125, value: 'Jersey', value2: 'Jersey', value3: 'JE' },
    { id: 126, value: 'Jordania', value2: 'Jordan', value3: 'JO' },
    { id: 127, value: 'Kazajistán', value2: 'Kazakhstan', value3: 'KZ' },
    { id: 128, value: 'Kenia', value2: 'Kenya', value3: 'KE' },
    { id: 129, value: 'Kirguistán', value2: 'Kyrgyzstan', value3: 'KG' },
    { id: 130, value: 'Kiribati', value2: 'Kiribati', value3: 'KI' },
    { id: 131, value: 'Kuwait', value2: 'Kuwait', value3: 'KW' },
    { id: 132, value: 'Líbano', value2: 'Lebanon', value3: 'LB' },
    { id: 133, value: 'Laos', value2: 'Laos', value3: 'LA' },
    { id: 134, value: 'Lesoto', value2: 'Lesotho', value3: 'LS' },
    { id: 135, value: 'Letonia', value2: 'Latvia', value3: 'LV' },
    { id: 136, value: 'Liberia', value2: 'Liberia', value3: 'LR' },
    { id: 137, value: 'Libia', value2: 'Libya', value3: 'LY' },
    { id: 138, value: 'Liechtenstein', value2: 'Liechtenstein', value3: 'LI' },
    { id: 139, value: 'Lituania', value2: 'Lithuania', value3: 'LT' },
    { id: 140, value: 'Luxemburgo', value2: 'Luxembourg', value3: 'LU' },
    { id: 141, value: 'México', value2: 'Mexico', value3: 'MX' },
    { id: 142, value: 'Mónaco', value2: 'Monaco', value3: 'MC' },
    { id: 143, value: 'Macao', value2: 'Macao', value3: 'MO' },
    { id: 144, value: 'Macedônia', value2: 'Macedonia', value3: 'MK' },
    { id: 145, value: 'Madagascar', value2: 'Madagascar', value3: 'MG' },
    { id: 146, value: 'Malasia', value2: 'Malaysia', value3: 'MY' },
    { id: 147, value: 'Malawi', value2: 'Malawi', value3: 'MW' },
    { id: 148, value: 'Mali', value2: 'Mali', value3: 'ML' },
    { id: 149, value: 'Malta', value2: 'Malta', value3: 'MT' },
    { id: 150, value: 'Marruecos', value2: 'Morocco', value3: 'MA' },
    { id: 151, value: 'Martinica', value2: 'Martinique', value3: 'MQ' },
    { id: 152, value: 'Mauricio', value2: 'Mauritius', value3: 'MU' },
    { id: 153, value: 'Mauritania', value2: 'Mauritania', value3: 'MR' },
    { id: 154, value: 'Mayotte', value2: 'Mayotte', value3: 'YT' },
    { id: 155, value: 'Micronesia', value2: 'Estados Federados de', value3: 'FM' },
    { id: 156, value: 'Moldavia', value2: 'Moldova', value3: 'MD' },
    { id: 157, value: 'Mongolia', value2: 'Mongolia', value3: 'MN' },
    { id: 158, value: 'Montenegro', value2: 'Montenegro', value3: 'ME' },
    { id: 159, value: 'Montserrat', value2: 'Montserrat', value3: 'MS' },
    { id: 160, value: 'Mozambique', value2: 'Mozambique', value3: 'MZ' },
    { id: 161, value: 'Namibia', value2: 'Namibia', value3: 'NA' },
    { id: 162, value: 'Nauru', value2: 'Nauru', value3: 'NR' },
    { id: 163, value: 'Nepal', value2: 'Nepal', value3: 'NP' },
    { id: 164, value: 'Nicaragua', value2: 'Nicaragua', value3: 'NI' },
    { id: 165, value: 'Niger', value2: 'Niger', value3: 'NE' },
    { id: 166, value: 'Nigeria', value2: 'Nigeria', value3: 'NG' },
    { id: 167, value: 'Niue', value2: 'Niue', value3: 'NU' },
    { id: 168, value: 'Noruega', value2: 'Norway', value3: 'NO' },
    { id: 169, value: 'Nueva Caledonia', value2: 'New Caledonia', value3: 'NC' },
    { id: 170, value: 'Nueva Zelanda', value2: 'New Zealand', value3: 'NZ' },
    { id: 171, value: 'Omán', value2: 'Oman', value3: 'OM' },
    { id: 172, value: 'Países Bajos', value2: 'Netherlands', value3: 'NL' },
    { id: 173, value: 'Pakistán', value2: 'Pakistan', value3: 'PK' },
    { id: 174, value: 'Palau', value2: 'Palau', value3: 'PW' },
    { id: 175, value: 'Palestina', value2: 'Palestine', value3: 'PS' },
    { id: 176, value: 'Panamá', value2: 'Panama', value3: 'PA' },
    { id: 177, value: 'Papúa Nueva Guinea', value2: 'Papua New Guinea', value3: 'PG' },
    { id: 178, value: 'Paraguay', value2: 'Paraguay', value3: 'PY' },
    { id: 179, value: 'Perú', value2: 'Peru', value3: 'PE' },
    { id: 180, value: 'Polinesia Francesa', value2: 'French Polynesia', value3: 'PF' },
    { id: 181, value: 'Polonia', value2: 'Poland', value3: 'PL' },
    { id: 182, value: 'Portugal', value2: 'Portugal', value3: 'PT' },
    { id: 183, value: 'Puerto Rico', value2: 'Puerto Rico', value3: 'PR' },
    { id: 184, value: 'Qatar', value2: 'Qatar', value3: 'QA' },
    { id: 185, value: 'Reino Unido', value2: 'United Kingdom', value3: 'GB' },
    { id: 186, value: 'República Centroafricana', value2: 'Central African Republic', value3: 'CF' },
    { id: 187, value: 'República Checa', value2: 'Czech Republic', value3: 'CZ' },
    { id: 188, value: 'República Dominicana', value2: 'Dominican Republic', value3: 'DO' },
    { id: 189, value: 'República de Sudán del Sur', value2: 'South Sudan', value3: 'SS' },
    { id: 190, value: 'Reunión', value2: 'Réunion', value3: 'RE' },
    { id: 191, value: 'Ruanda', value2: 'Rwanda', value3: 'RW' },
    { id: 192, value: 'Rumanía', value2: 'Romania', value3: 'RO' },
    { id: 193, value: 'Rusia', value2: 'Russia', value3: 'RU' },
    { id: 194, value: 'Sahara Occidental', value2: 'Western Sahara', value3: 'EH' },
    { id: 195, value: 'Samoa', value2: 'Samoa', value3: 'WS' },
    { id: 196, value: 'Samoa Americana', value2: 'American Samoa', value3: 'AS' },
    { id: 197, value: 'San Bartolomé', value2: 'Saint Barthélemy', value3: 'BL' },
    { id: 198, value: 'San Cristóbal y Nieves', value2: 'Saint Kitts and Nevis', value3: 'KN' },
    { id: 199, value: 'San Marino', value2: 'San Marino', value3: 'SM' },
    { id: 200, value: 'San Martín (Francia)', value2: 'Saint Martin (French part)', value3: 'MF' },
    { id: 201, value: 'San Pedro y Miquelón', value2: 'Saint Pierre and Miquelon', value3: 'PM' },
    { id: 202, value: 'San Vicente y las Granadinas', value2: 'Saint Vincent and the Grenadines', value3: 'VC' },
    { id: 203, value: 'Santa Elena', value2: 'Ascensión y Tristán de Acuña', value3: 'SH' },
    { id: 204, value: 'Santa Lucía', value2: 'Saint Lucia', value3: 'LC' },
    { id: 205, value: 'Santo Tomé y Príncipe', value2: 'Sao Tome and Principe', value3: 'ST' },
    { id: 206, value: 'Senegal', value2: 'Senegal', value3: 'SN' },
    { id: 207, value: 'Serbia', value2: 'Serbia', value3: 'RS' },
    { id: 208, value: 'Seychelles', value2: 'Seychelles', value3: 'SC' },
    { id: 209, value: 'Sierra Leona', value2: 'Sierra Leone', value3: 'SL' },
    { id: 210, value: 'Singapur', value2: 'Singapore', value3: 'SG' },
    { id: 211, value: 'Sint Maarten', value2: 'Sint Maarten', value3: 'SX' },
    { id: 212, value: 'Siria', value2: 'Syria', value3: 'SY' },
    { id: 213, value: 'Somalia', value2: 'Somalia', value3: 'SO' },
    { id: 214, value: 'Sri lanka', value2: 'Sri Lanka', value3: 'LK' },
    { id: 215, value: 'Sudáfrica', value2: 'South Africa', value3: 'ZA' },
    { id: 216, value: 'Sudán', value2: 'Sudan', value3: 'SD' },
    { id: 217, value: 'Suecia', value2: 'Sweden', value3: 'SE' },
    { id: 218, value: 'Suiza', value2: 'Switzerland', value3: 'CH' },
    { id: 219, value: 'Surinám', value2: 'Suriname', value3: 'SR' },
    { id: 220, value: 'Svalbard y Jan Mayen', value2: 'Svalbard and Jan Mayen', value3: 'SJ' },
    { id: 221, value: 'Swazilandia', value2: 'Swaziland', value3: 'SZ' },
    { id: 222, value: 'Tayikistán', value2: 'Tajikistan', value3: 'TJ' },
    { id: 223, value: 'Tailandia', value2: 'Thailand', value3: 'TH' },
    { id: 224, value: 'Taiwán', value2: 'Taiwan', value3: 'TW' },
    { id: 225, value: 'Tanzania', value2: 'Tanzania', value3: 'TZ' },
    { id: 226, value: 'Territorio Británico del Océano Índico', value2: 'British Indian Ocean Territory', value3: 'IO' },
    { id: 227, value: 'Territorios Australes y Antárticas Franceses', value2: 'French Southern Territories', value3: 'TF' },
    { id: 228, value: 'Timor Oriental', value2: 'East Timor', value3: 'TL' },
    { id: 229, value: 'Togo', value2: 'Togo', value3: 'TG' },
    { id: 230, value: 'Tokelau', value2: 'Tokelau', value3: 'TK' },
    { id: 231, value: 'Tonga', value2: 'Tonga', value3: 'TO' },
    { id: 232, value: 'Trinidad y Tobago', value2: 'Trinidad and Tobago', value3: 'TT' },
    { id: 233, value: 'Tunez', value2: 'Tunisia', value3: 'TN' },
    { id: 234, value: 'Turkmenistán', value2: 'Turkmenistan', value3: 'TM' },
    { id: 235, value: 'Turquía', value2: 'Turkey', value3: 'TR' },
    { id: 236, value: 'Tuvalu', value2: 'Tuvalu', value3: 'TV' },
    { id: 237, value: 'Ucrania', value2: 'Ukraine', value3: 'UA' },
    { id: 238, value: 'Uganda', value2: 'Uganda', value3: 'UG' },
    { id: 239, value: 'Uruguay', value2: 'Uruguay', value3: 'UY' },
    { id: 240, value: 'Uzbekistán', value2: 'Uzbekistan', value3: 'UZ' },
    { id: 241, value: 'Vanuatu', value2: 'Vanuatu', value3: 'VU' },
    { id: 242, value: 'Venezuela', value2: 'Venezuela', value3: 'VE' },
    { id: 243, value: 'Vietnam', value2: 'Vietnam', value3: 'VN' },
    { id: 244, value: 'Wallis y Futuna', value2: 'Wallis and Futuna', value3: 'WF' },
    { id: 245, value: 'Yemen', value2: 'Yemen', value3: 'YE' },
    { id: 246, value: 'Yibuti', value2: 'Djibouti', value3: 'DJ' },
    { id: 247, value: 'Zambia', value2: 'Zambia', value3: 'ZM' },
    { id: 248, value: 'Zimbabue', value2: 'Zimbabwe', value3: 'ZW' }
];