import { Data } from "./data";

export const PARROQUIAS: Data[] = [
    { id: 1, value: '23 de Enero', value2: '', value3: '' },
    { id: 2, value: 'Altagracia', value2: '', value3: '' },
    { id: 3, value: 'Antímano', value2: '', value3: '' },
    { id: 4, value: 'Caricuao', value2: '', value3: '' },
    { id: 5, value: 'Catedral', value2: '', value3: '' },
    { id: 6, value: 'Coche', value2: '', value3: '' },
    { id: 7, value: 'El Junquito', value2: '', value3: '' },
    { id: 8, value: 'El Paraíso', value2: '', value3: '' },
    { id: 9, value: 'El Recreo', value2: '', value3: '' },
    { id: 10, value: 'El Valle', value2: '', value3: '' },
    { id: 11, value: 'Candelaria', value2: '', value3: '' },
    { id: 12, value: 'La Pastora', value2: '', value3: '' },
    { id: 13, value: 'La Vega', value2: '', value3: '' },
    { id: 14, value: 'Macarao', value2: '', value3: '' },
    { id: 15, value: 'San Agustín', value2: '', value3: '' },
    { id: 16, value: 'San Bernardino', value2: '', value3: '' },
    { id: 17, value: 'San José', value2: '', value3: '' },
    { id: 18, value: 'San Juan', value2: '', value3: '' },
    { id: 19, value: 'San Pedro', value2: '', value3: '' },
    { id: 20, value: 'Santa Rosalia', value2: '', value3: '' },
    { id: 21, value: 'Santa Teresa', value2: '', value3: '' },
    { id: 22, value: 'Sucre', value2: '', value3: '' },
    { id: 23, value: 'Alto Orinoco', value2: '', value3: '' },
    { id: 24, value: 'Huachamacare', value2: '', value3: '' },
    { id: 25, value: 'Marawaka', value2: '', value3: '' },
    { id: 26, value: 'Mavaka', value2: '', value3: '' },
    { id: 27, value: 'Sierra Parima', value2: '', value3: '' },
    { id: 28, value: 'Atabapo', value2: '', value3: '' },
    { id: 29, value: 'Ucata', value2: '', value3: '' },
    { id: 30, value: 'Yapacana', value2: '', value3: '' },
    { id: 31, value: 'Caname', value2: '', value3: '' },
    { id: 32, value: 'Fernando Girón Tovar', value2: '', value3: '' },
    { id: 33, value: 'Luis Alberto Gómez', value2: '', value3: '' },
    { id: 34, value: 'Pahueña', value2: '', value3: '' },
    { id: 35, value: 'Platanillal', value2: '', value3: '' },
    { id: 36, value: 'Samariapo', value2: '', value3: '' },
    { id: 37, value: 'Sipapo', value2: '', value3: '' },
    { id: 38, value: 'Munduapo', value2: '', value3: '' },
    { id: 39, value: 'Guayapo', value2: '', value3: '' },
    { id: 40, value: 'Isla Ratón', value2: '', value3: '' },
    { id: 41, value: 'Alto Ventuari', value2: '', value3: '' },
    { id: 42, value: 'Medio Ventuari', value2: '', value3: '' },
    { id: 43, value: 'Bajo Ventuari', value2: '', value3: '' },
    { id: 44, value: 'Manapiare', value2: '', value3: '' },
    { id: 45, value: 'Maroa', value2: '', value3: '' },
    { id: 46, value: 'Victorino', value2: '', value3: '' },
    { id: 47, value: 'Comunidad', value2: '', value3: '' },
    { id: 48, value: 'Casiquiare', value2: '', value3: '' },
    { id: 49, value: 'Cocuy', value2: '', value3: '' },
    { id: 50, value: 'San Carlos de Río Negro', value2: '', value3: '' },
    { id: 51, value: 'Solano', value2: '', value3: '' },
    { id: 52, value: 'Anaco', value2: '', value3: '' },
    { id: 53, value: 'San Joaquín', value2: '', value3: '' },
    { id: 54, value: 'Buena Vista', value2: '', value3: '' },
    { id: 55, value: 'Cachipo', value2: '', value3: '' },
    { id: 56, value: 'Aragua de Barcelona', value2: '', value3: '' },
    { id: 57, value: 'Lechería', value2: '', value3: '' },
    { id: 58, value: 'El Morro', value2: '', value3: '' },
    { id: 59, value: 'Puerto Píritu', value2: '', value3: '' },
    { id: 60, value: 'San Miguel', value2: '', value3: '' },
    { id: 61, value: 'Valle de Guanape', value2: '', value3: '' },
    { id: 62, value: 'Santa Bárbara', value2: '', value3: '' },
    { id: 63, value: 'Atapirire', value2: '', value3: '' },
    { id: 64, value: 'Boca del Pao', value2: '', value3: '' },
    { id: 65, value: 'El Pao', value2: '', value3: '' },
    { id: 66, value: 'Pariaguán', value2: '', value3: '' },
    { id: 67, value: 'Guanta', value2: '', value3: '' },
    { id: 68, value: 'Chorrerón', value2: '', value3: '' },
    { id: 69, value: 'Mamo', value2: '', value3: '' },
    { id: 70, value: 'Soledad', value2: '', value3: '' },
    { id: 71, value: 'Mapire', value2: '', value3: '' },
    { id: 72, value: 'Piar', value2: '', value3: '' },
    { id: 73, value: 'Santa Clara', value2: '', value3: '' },
    { id: 74, value: 'San Diego de Cabrutica', value2: '', value3: '' },
    { id: 75, value: 'Uverito', value2: '', value3: '' },
    { id: 76, value: 'Zuata', value2: '', value3: '' },
    { id: 77, value: 'Puerto La Cruz', value2: '', value3: '' },
    { id: 78, value: 'Pozuelos', value2: '', value3: '' },
    { id: 79, value: 'Onoto', value2: '', value3: '' },
    { id: 80, value: 'San Pablo', value2: '', value3: '' },
    { id: 81, value: 'San Mateo', value2: '', value3: '' },
    { id: 82, value: 'El Carito', value2: '', value3: '' },
    { id: 83, value: 'Santa Inés', value2: '', value3: '' },
    { id: 84, value: 'La Romereña', value2: '', value3: '' },
    { id: 85, value: 'Clarines', value2: '', value3: '' },
    { id: 86, value: 'Guanape', value2: '', value3: '' },
    { id: 87, value: 'Sabana de Uchire', value2: '', value3: '' },
    { id: 88, value: 'Cantaura', value2: '', value3: '' },
    { id: 89, value: 'Libertador', value2: '', value3: '' },
    { id: 90, value: 'Santa Rosa', value2: '', value3: '' },
    { id: 91, value: 'Urica', value2: '', value3: '' },
    { id: 92, value: 'Píritu', value2: '', value3: '' },
    { id: 93, value: 'San Francisco', value2: '', value3: '' },
    { id: 94, value: 'San José de Guanipa', value2: '', value3: '' },
    { id: 95, value: 'Boca de Uchire', value2: '', value3: '' },
    { id: 96, value: 'Boca de Chávez', value2: '', value3: '' },
    { id: 97, value: 'Pueblo Nuevo', value2: '', value3: '' },
    { id: 98, value: 'Santa Ana', value2: '', value3: '' },
    { id: 99, value: 'Bergantín', value2: '', value3: '' },
    { id: 100, value: 'Caigua', value2: '', value3: '' },
    { id: 101, value: 'El Carmen.', value2: '', value3: '' },
    { id: 102, value: 'El Pilar', value2: '', value3: '' },
    { id: 103, value: 'Naricual.', value2: '', value3: '' },
    { id: 104, value: 'San Cristóbal', value2: '', value3: '' },
    { id: 105, value: 'Edmundo Barrios', value2: '', value3: '' },
    { id: 106, value: 'Miguel Otero Silva', value2: '', value3: '' },
    { id: 107, value: 'El Chaparro', value2: '', value3: '' },
    { id: 108, value: 'Tomás Alfaro', value2: '', value3: '' },
    { id: 109, value: 'Calatrava', value2: '', value3: '' },
    { id: 110, value: 'Achaguas', value2: '', value3: '' },
    { id: 111, value: 'Apurito', value2: '', value3: '' },
    { id: 112, value: 'El Yagual', value2: '', value3: '' },
    { id: 113, value: 'Guachara', value2: '', value3: '' },
    { id: 114, value: 'Mucuritas', value2: '', value3: '' },
    { id: 115, value: 'Queseras del medio', value2: '', value3: '' },
    { id: 116, value: 'Biruaca', value2: '', value3: '' },
    { id: 117, value: 'Bruzual', value2: '', value3: '' },
    { id: 118, value: 'Mantecal', value2: '', value3: '' },
    { id: 119, value: 'Quintero', value2: '', value3: '' },
    { id: 120, value: 'Rincón Hondo', value2: '', value3: '' },
    { id: 121, value: 'San Vicente', value2: '', value3: '' },
    { id: 122, value: 'San Juan de Payara', value2: '', value3: '' },
    { id: 123, value: 'Codazzi', value2: '', value3: '' },
    { id: 124, value: 'Cunaviche', value2: '', value3: '' },
    { id: 125, value: 'San Fernando', value2: '', value3: '' },
    { id: 126, value: 'Peñalver', value2: '', value3: '' },
    { id: 127, value: 'San Rafael de Atamaica', value2: '', value3: '' },
    { id: 128, value: 'Distrito Alto Apure', value2: '', value3: '' },
    { id: 129, value: 'Guasdualito', value2: '', value3: '' },
    { id: 130, value: 'Aramendi', value2: '', value3: '' },
    { id: 131, value: 'El Amparo', value2: '', value3: '' },
    { id: 132, value: 'San Camilo', value2: '', value3: '' },
    { id: 133, value: 'Urdaneta', value2: '', value3: '' },
    { id: 134, value: 'Elorza', value2: '', value3: '' },
    { id: 135, value: 'La Trinidad', value2: '', value3: '' },
    { id: 136, value: 'Bolívar', value2: '', value3: '' },
    { id: 137, value: 'Camatagua', value2: '', value3: '' },
    { id: 138, value: 'Carmen de Cura, (es una tribu)', value2: '', value3: '' },
    { id: 139, value: 'Santa Rita', value2: '', value3: '' },
    { id: 140, value: 'Francisco de Miranda', value2: '', value3: '' },
    { id: 141, value: 'Moseñor Feliciano González', value2: '', value3: '' },
    { id: 142, value: 'Pedro José Ovalles', value2: '', value3: '' },
    { id: 143, value: 'Joaquín Crespo', value2: '', value3: '' },
    { id: 144, value: 'José Casanova Godoy', value2: '', value3: '' },
    { id: 145, value: 'Madre María de San José', value2: '', value3: '' },
    { id: 146, value: 'Andrés Eloy Blanco', value2: '', value3: '' },
    { id: 147, value: 'Los Tacarigua', value2: '', value3: '' },
    { id: 148, value: 'Las Delicias', value2: '', value3: '' },
    { id: 149, value: 'Choroní', value2: '', value3: '' },
    { id: 150, value: 'Santa Cruz', value2: '', value3: '' },
    { id: 151, value: 'José Félix Ribas', value2: '', value3: '' },
    { id: 152, value: 'Castor Nieves Ríos', value2: '', value3: '' },
    { id: 153, value: 'Las Guacamayas', value2: '', value3: '' },
    { id: 154, value: 'Pao de Zárate', value2: '', value3: '' },
    { id: 155, value: 'José Rafael Revenga', value2: '', value3: '' },
    { id: 156, value: 'El Consejo', value2: '', value3: '' },
    { id: 157, value: 'Palo Negro', value2: '', value3: '' },
    { id: 158, value: 'San Martín de Porres', value2: '', value3: '' },
    { id: 159, value: 'El Limón', value2: '', value3: '' },
    { id: 160, value: 'Caña de Azúcar', value2: '', value3: '' },
    { id: 161, value: 'Ocumare de la Costa', value2: '', value3: '' },
    { id: 162, value: 'San Casimiro', value2: '', value3: '' },
    { id: 163, value: 'San Sebastían', value2: '', value3: '' },
    { id: 164, value: 'Turmero', value2: '', value3: '' },
    { id: 165, value: 'Arévalo Aponte', value2: '', value3: '' },
    { id: 166, value: 'Chuao', value2: '', value3: '' },
    { id: 167, value: 'Samán de Güere', value2: '', value3: '' },
    { id: 168, value: 'Alfredo Pacheco Miranda', value2: '', value3: '' },
    { id: 169, value: 'Santos Michelena', value2: '', value3: '' },
    { id: 170, value: 'Tiara', value2: '', value3: '' },
    { id: 171, value: 'Cagua', value2: '', value3: '' },
    { id: 172, value: 'Bella Vista', value2: '', value3: '' },
    { id: 173, value: 'Tovar', value2: '', value3: '' },
    { id: 174, value: 'Las Peñitas', value2: '', value3: '' },
    { id: 175, value: 'San Francisco de Cara', value2: '', value3: '' },
    { id: 176, value: 'Taguay', value2: '', value3: '' },
    { id: 177, value: 'Villa de Cura', value2: '', value3: '' },
    { id: 178, value: 'Magdaleno', value2: '', value3: '' },
    { id: 179, value: 'San Francisco de Asís', value2: '', value3: '' },
    { id: 180, value: 'Valles de Tucutunemo', value2: '', value3: '' },
    { id: 181, value: 'Augusto Mijares', value2: '', value3: '' },
    { id: 182, value: 'Sabaneta', value2: '', value3: '' },
    { id: 183, value: 'Juan Antonio Rodríguez Domínguez', value2: '', value3: '' },
    { id: 184, value: 'El Cantón', value2: '', value3: '' },
    { id: 185, value: 'Santa Cruz de Guacas', value2: '', value3: '' },
    { id: 186, value: 'Puerto Vivas', value2: '', value3: '' },
    { id: 187, value: 'Socopo', value2: '', value3: '' },
    { id: 188, value: 'Nicolás Pulido', value2: '', value3: '' },
    { id: 189, value: 'Andrés Bello', value2: '', value3: '' },
    { id: 190, value: 'Arismendi', value2: '', value3: '' },
    { id: 191, value: 'Guadarrama', value2: '', value3: '' },
    { id: 192, value: 'La Unión', value2: '', value3: '' },
    { id: 193, value: 'San Antonio', value2: '', value3: '' },
    { id: 194, value: 'Barinas', value2: '', value3: '' },
    { id: 195, value: 'Barinitas', value2: '', value3: '' },
    { id: 196, value: 'Barrancas', value2: '', value3: '' },
    { id: 197, value: 'El Socorro', value2: '', value3: '' },
    { id: 198, value: 'Mazparrito', value2: '', value3: '' },
    { id: 199, value: 'Pedro Briceño Méndez', value2: '', value3: '' },
    { id: 200, value: 'Ramón Ignacio Méndez', value2: '', value3: '' },
    { id: 201, value: 'José Ignacio del Pumar', value2: '', value3: '' },
    { id: 202, value: 'Obispos', value2: '', value3: '' },
    { id: 203, value: 'Ciudad Bolivia', value2: '', value3: '' },
    { id: 204, value: 'Libertad', value2: '', value3: '' },
    { id: 205, value: 'Dolores', value2: '', value3: '' },
    { id: 206, value: 'Palacio Fajardo', value2: '', value3: '' },
    { id: 207, value: 'Simón Rodríguez', value2: '', value3: '' },
    { id: 208, value: 'Ciudad de Nutrias', value2: '', value3: '' },
    { id: 209, value: 'El Regalo', value2: '', value3: '' },
    { id: 210, value: 'Puerto Nutrias', value2: '', value3: '' },
    { id: 211, value: 'Santa Catalina', value2: '', value3: '' },
    { id: 212, value: 'Simón Bolívar', value2: '', value3: '' },
    { id: 213, value: 'Cachamay', value2: '', value3: '' },
    { id: 214, value: 'Chirica', value2: '', value3: '' },
    { id: 215, value: 'Dalla Costa', value2: '', value3: '' },
    { id: 216, value: 'Once de Abril', value2: '', value3: '' },
    { id: 217, value: 'Unare', value2: '', value3: '' },
    { id: 218, value: 'Universidad', value2: '', value3: '' },
    { id: 219, value: 'Vista al Sol', value2: '', value3: '' },
    { id: 220, value: 'Pozo Verde', value2: '', value3: '' },
    { id: 221, value: 'Yocoima', value2: '', value3: '' },
    { id: 222, value: '5 de Julio', value2: '', value3: '' },
    { id: 223, value: 'Pto. Ordaz', value2: '', value3: '' },
    { id: 224, value: 'Cedeño', value2: '', value3: '' },
    { id: 225, value: 'Ascensión Farreras', value2: '', value3: '' },
    { id: 226, value: 'Guaniamo', value2: '', value3: '' },
    { id: 227, value: 'La Urbana', value2: '', value3: '' },
    { id: 228, value: 'Pijiguaos', value2: '', value3: '' },
    { id: 229, value: 'El Callao', value2: '', value3: '' },
    { id: 230, value: 'Gran Sabana', value2: '', value3: '' },
    { id: 231, value: 'IkabaRú', value2: '', value3: '' },
    { id: 232, value: 'Zea', value2: '', value3: '' },
    { id: 233, value: 'Orinoco', value2: '', value3: '' },
    { id: 234, value: 'José Antonio Páez', value2: '', value3: '' },
    { id: 235, value: 'Marhuanta', value2: '', value3: '' },
    { id: 236, value: 'Agua Salada', value2: '', value3: '' },
    { id: 237, value: 'Vista Hermosa', value2: '', value3: '' },
    { id: 238, value: 'La Sabanita', value2: '', value3: '' },
    { id: 239, value: 'Panapana', value2: '', value3: '' },
    { id: 240, value: 'Padre Pedro Chien', value2: '', value3: '' },
    { id: 241, value: 'Pedro Cova', value2: '', value3: '' },
    { id: 242, value: 'Upata', value2: '', value3: '' },
    { id: 243, value: 'Raúl Leoni', value2: '', value3: '' },
    { id: 244, value: 'Barceloneta', value2: '', value3: '' },
    { id: 245, value: 'Roscio', value2: '', value3: '' },
    { id: 246, value: 'Salóm', value2: '', value3: '' },
    { id: 247, value: 'Tumeremo', value2: '', value3: '' },
    { id: 248, value: 'San Isidro', value2: '', value3: '' },
    { id: 249, value: 'Aripao', value2: '', value3: '' },
    { id: 250, value: 'Guarataro', value2: '', value3: '' },
    { id: 251, value: 'Las Majadas', value2: '', value3: '' },
    { id: 252, value: 'Moitaco', value2: '', value3: '' },
    { id: 253, value: 'Canoabo', value2: '', value3: '' },
    { id: 254, value: 'Güigüe', value2: '', value3: '' },
    { id: 255, value: 'Belén', value2: '', value3: '' },
    { id: 256, value: 'Tacarigua', value2: '', value3: '' },
    { id: 257, value: 'Mariara', value2: '', value3: '' },
    { id: 258, value: 'Aguas Calientes', value2: '', value3: '' },
    { id: 259, value: 'Ciudad Alianza', value2: '', value3: '' },
    { id: 260, value: 'Guacara', value2: '', value3: '' },
    { id: 261, value: 'Yagua', value2: '', value3: '' },
    { id: 262, value: 'Morón', value2: '', value3: '' },
    { id: 263, value: 'Urama', value2: '', value3: '' },
    { id: 264, value: 'Tocuyito Valencia', value2: '', value3: '' },
    { id: 265, value: 'Independencia Campo Carabobo', value2: '', value3: '' },
    { id: 266, value: 'Los Guayos Valencia', value2: '', value3: '' },
    { id: 267, value: 'Miranda', value2: '', value3: '' },
    { id: 268, value: 'Montalbán', value2: '', value3: '' },
    { id: 269, value: 'Urbana Naguanagua Valencia', value2: '', value3: '' },
    { id: 270, value: 'Bartolomé Salóm', value2: '', value3: '' },
    { id: 271, value: 'Democracia', value2: '', value3: '' },
    { id: 272, value: 'Fraternidad', value2: '', value3: '' },
    { id: 273, value: 'Goaigoaza', value2: '', value3: '' },
    { id: 274, value: 'Juan José Flores', value2: '', value3: '' },
    { id: 275, value: 'Unión', value2: '', value3: '' },
    { id: 276, value: 'Borburata', value2: '', value3: '' },
    { id: 277, value: 'Patanemo', value2: '', value3: '' },
    { id: 278, value: 'San Diego Valencia', value2: '', value3: '' },
    { id: 279, value: 'Urbana Candelaria', value2: '', value3: '' },
    { id: 280, value: 'Urbana Catedral', value2: '', value3: '' },
    { id: 281, value: 'Urbana El Socorro', value2: '', value3: '' },
    { id: 282, value: 'Urbana Miguel Peña', value2: '', value3: '' },
    { id: 283, value: 'Urbana Rafael Urdaneta', value2: '', value3: '' },
    { id: 284, value: 'Urbana San Blas', value2: '', value3: '' },
    { id: 285, value: 'Urbana San José', value2: '', value3: '' },
    { id: 286, value: 'Urbana Santa Rosa', value2: '', value3: '' },
    { id: 287, value: 'No Urbana Negro Primero', value2: '', value3: '' },
    { id: 288, value: 'Cojedes', value2: '', value3: '' },
    { id: 289, value: 'Juan de Mata Suárez', value2: '', value3: '' },
    { id: 290, value: 'Tinaquillo', value2: '', value3: '' },
    { id: 291, value: 'El Baúl', value2: '', value3: '' },
    { id: 292, value: 'La Aguadita', value2: '', value3: '' },
    { id: 293, value: 'Macapo', value2: '', value3: '' },
    { id: 294, value: 'Libertad de Cojedes', value2: '', value3: '' },
    { id: 295, value: 'Rómulo Gallegos', value2: '', value3: '' },
    { id: 296, value: 'San Carlos de Austria', value2: '', value3: '' },
    { id: 297, value: 'Juan Ángel Bravo', value2: '', value3: '' },
    { id: 298, value: 'Manuel Manrique', value2: '', value3: '' },
    { id: 299, value: 'General en Jefe José Laurencio Silva', value2: '', value3: '' },
    { id: 300, value: 'Curiapo', value2: '', value3: '' },
    { id: 301, value: 'Almirante Luis Brión', value2: '', value3: '' },
    { id: 302, value: 'Francisco Aniceto Lugo', value2: '', value3: '' },
    { id: 303, value: 'Manuel Renaud', value2: '', value3: '' },
    { id: 304, value: 'Padre Barral', value2: '', value3: '' },
    { id: 305, value: 'Santos de Abelgas', value2: '', value3: '' },
    { id: 306, value: 'Imataca', value2: '', value3: '' },
    { id: 307, value: 'Juan Bautista Arismendi', value2: '', value3: '' },
    { id: 308, value: 'Manuel Piar', value2: '', value3: '' },
    { id: 309, value: 'Pedernales', value2: '', value3: '' },
    { id: 310, value: 'Luis Beltrán Prieto Figueroa', value2: '', value3: '' },
    { id: 311, value: 'José Vidal Marcano', value2: '', value3: '' },
    { id: 312, value: 'Leonardo Ruíz Pineda', value2: '', value3: '' },
    { id: 313, value: 'Mariscal Antonio José de Sucre', value2: '', value3: '' },
    { id: 314, value: 'Monseñor Argimiro García', value2: '', value3: '' },
    { id: 315, value: 'Virgen del Valle', value2: '', value3: '' },
    { id: 316, value: 'San Rafael', value2: '', value3: '' },
    { id: 317, value: 'Juan Millan', value2: '', value3: '' },
    { id: 318, value: 'Capadare', value2: '', value3: '' },
    { id: 319, value: 'San Juan de los Cayos', value2: '', value3: '' },
    { id: 320, value: 'Aracua', value2: '', value3: '' },
    { id: 321, value: 'La Peña', value2: '', value3: '' },
    { id: 322, value: 'San Luis', value2: '', value3: '' },
    { id: 323, value: 'Bariro', value2: '', value3: '' },
    { id: 324, value: 'Borojó', value2: '', value3: '' },
    { id: 325, value: 'Capatárida', value2: '', value3: '' },
    { id: 326, value: 'Guajiro', value2: '', value3: '' },
    { id: 327, value: 'Seque', value2: '', value3: '' },
    { id: 328, value: 'Valle de Eroa', value2: '', value3: '' },
    { id: 329, value: 'Zazárida', value2: '', value3: '' },
    { id: 330, value: 'Cacique Manaure', value2: '', value3: '' },
    { id: 331, value: 'Norte', value2: '', value3: '' },
    { id: 332, value: 'Carirubana', value2: '', value3: '' },
    { id: 333, value: 'Urbana Punta Cardón', value2: '', value3: '' },
    { id: 334, value: 'La Vela de Coro', value2: '', value3: '' },
    { id: 335, value: 'Acurigua', value2: '', value3: '' },
    { id: 336, value: 'Guaibacoa', value2: '', value3: '' },
    { id: 337, value: 'Las Calderas', value2: '', value3: '' },
    { id: 338, value: 'Mataruca', value2: '', value3: '' },
    { id: 339, value: 'Dabajuro', value2: '', value3: '' },
    { id: 340, value: 'Agua Clara', value2: '', value3: '' },
    { id: 341, value: 'Avaria', value2: '', value3: '' },
    { id: 342, value: 'Pedregal', value2: '', value3: '' },
    { id: 343, value: 'Piedra Grande', value2: '', value3: '' },
    { id: 344, value: 'Purureche', value2: '', value3: '' },
    { id: 345, value: 'Adaure', value2: '', value3: '' },
    { id: 346, value: 'Adícora', value2: '', value3: '' },
    { id: 347, value: 'Baraived', value2: '', value3: '' },
    { id: 348, value: 'Jadacaquiva', value2: '', value3: '' },
    { id: 349, value: 'El Vínculo', value2: '', value3: '' },
    { id: 350, value: 'El Hato', value2: '', value3: '' },
    { id: 351, value: 'Moruy', value2: '', value3: '' },
    { id: 352, value: 'Agua Larga', value2: '', value3: '' },
    { id: 353, value: 'Churuguara', value2: '', value3: '' },
    { id: 354, value: 'El Paují', value2: '', value3: '' },
    { id: 355, value: 'Independencia', value2: '', value3: '' },
    { id: 356, value: 'Mapararí', value2: '', value3: '' },
    { id: 357, value: 'Agua Linda', value2: '', value3: '' },
    { id: 358, value: 'Araurima', value2: '', value3: '' },
    { id: 359, value: 'Jacura', value2: '', value3: '' },
    { id: 360, value: 'Los Taques', value2: '', value3: '' },
    { id: 361, value: 'Judibana', value2: '', value3: '' },
    { id: 362, value: 'Mene de Mauroa', value2: '', value3: '' },
    { id: 363, value: 'San Félix', value2: '', value3: '' },
    { id: 364, value: 'Casigua', value2: '', value3: '' },
    { id: 365, value: 'Guzmán Guillermo', value2: '', value3: '' },
    { id: 366, value: 'Mitare', value2: '', value3: '' },
    { id: 367, value: 'Río Seco', value2: '', value3: '' },
    { id: 368, value: 'San Gabriel', value2: '', value3: '' },
    { id: 369, value: 'Boca del Tocuyo', value2: '', value3: '' },
    { id: 370, value: 'Chichiriviche', value2: '', value3: '' },
    { id: 371, value: 'Tocuyo de la Costa', value2: '', value3: '' },
    { id: 372, value: 'Palmasola', value2: '', value3: '' },
    { id: 373, value: 'Cabure', value2: '', value3: '' },
    { id: 374, value: 'Colina', value2: '', value3: '' },
    { id: 375, value: 'Curimagua', value2: '', value3: '' },
    { id: 376, value: 'San José de la Costa', value2: '', value3: '' },
    { id: 377, value: 'Capital San Francisco Mirimire', value2: '', value3: '' },
    { id: 378, value: 'Tucacas', value2: '', value3: '' },
    { id: 379, value: 'Boca de Aroa', value2: '', value3: '' },
    { id: 380, value: 'Pecaya', value2: '', value3: '' },
    { id: 381, value: 'Tocópero', value2: '', value3: '' },
    { id: 382, value: 'El Charal', value2: '', value3: '' },
    { id: 383, value: 'Las Vegas del Tuy', value2: '', value3: '' },
    { id: 384, value: 'Santa Cruz de Bucaral', value2: '', value3: '' },
    { id: 385, value: 'Urumaco', value2: '', value3: '' },
    { id: 386, value: 'Puerto Cumarebo', value2: '', value3: '' },
    { id: 387, value: 'La Ciénaga', value2: '', value3: '' },
    { id: 388, value: 'La Soledad', value2: '', value3: '' },
    { id: 389, value: 'Pueblo Cumarebo', value2: '', value3: '' },
    { id: 390, value: 'Camaguán', value2: '', value3: '' },
    { id: 391, value: 'Puerto Miranda', value2: '', value3: '' },
    { id: 392, value: 'Chaguaramas', value2: '', value3: '' },
    { id: 393, value: 'El Calvario', value2: '', value3: '' },
    { id: 394, value: 'El Rastro', value2: '', value3: '' },
    { id: 395, value: 'Guardatinajas', value2: '', value3: '' },
    { id: 396, value: 'Capital Urbana Calabozo', value2: '', value3: '' },
    { id: 397, value: 'Tucupido', value2: '', value3: '' },
    { id: 398, value: 'San Rafael de Laya', value2: '', value3: '' },
    { id: 399, value: 'Altagracia de Orituco.', value2: '', value3: '' },
    { id: 400, value: 'San Rafael de Orituco.', value2: '', value3: '' },
    { id: 401, value: 'San Francisco Javier de Lezama.', value2: '', value3: '' },
    { id: 402, value: 'Paso Real de Macaira.', value2: '', value3: '' },
    { id: 403, value: 'Carlos Soublette.', value2: '', value3: '' },
    { id: 404, value: 'San Francisco de Macaira.', value2: '', value3: '' },
    { id: 405, value: 'Libertad de Orituco.', value2: '', value3: '' },
    { id: 406, value: 'Cantagallo', value2: '', value3: '' },
    { id: 407, value: 'San Juan de Los Morros', value2: '', value3: '' },
    { id: 408, value: 'Parapara', value2: '', value3: '' },
    { id: 409, value: 'El Sombrero', value2: '', value3: '' },
    { id: 410, value: 'Sosa', value2: '', value3: '' },
    { id: 411, value: 'Las Mercedes', value2: '', value3: '' },
    { id: 412, value: 'Cabruta', value2: '', value3: '' },
    { id: 413, value: 'Santa Rita de Manapire', value2: '', value3: '' },
    { id: 414, value: 'Valle de la Pascua', value2: '', value3: '' },
    { id: 415, value: 'Espino', value2: '', value3: '' },
    { id: 416, value: 'San José de Tiznados', value2: '', value3: '' },
    { id: 417, value: 'San Francisco de Tiznados', value2: '', value3: '' },
    { id: 418, value: 'San Lorenzo de Tiznados', value2: '', value3: '' },
    { id: 419, value: 'Ortiz', value2: '', value3: '' },
    { id: 420, value: 'San José de Unare', value2: '', value3: '' },
    { id: 421, value: 'Zaraza', value2: '', value3: '' },
    { id: 422, value: 'Guayabal', value2: '', value3: '' },
    { id: 423, value: 'Cazorla', value2: '', value3: '' },
    { id: 424, value: 'San José de Guaribe', value2: '', value3: '' },
    { id: 425, value: 'Santa María de Ipire', value2: '', value3: '' },
    { id: 426, value: 'Altamira', value2: '', value3: '' },
    { id: 427, value: 'Quebrada Honda de Guache', value2: '', value3: '' },
    { id: 428, value: 'Pio Tamayo', value2: '', value3: '' },
    { id: 429, value: 'Yacambú', value2: '', value3: '' },
    { id: 430, value: 'Freitez', value2: '', value3: '' },
    { id: 431, value: 'José María Blanco', value2: '', value3: '' },
    { id: 432, value: 'Aguedo Felipe Alvarado', value2: '', value3: '' },
    { id: 433, value: 'Concepción', value2: '', value3: '' },
    { id: 434, value: 'El Cují', value2: '', value3: '' },
    { id: 435, value: 'Juárez', value2: '', value3: '' },
    { id: 436, value: 'Ana Soto (Antigua Juan de Villegas)', value2: '', value3: '' },
    { id: 437, value: 'Tamaca', value2: '', value3: '' },
    { id: 438, value: 'Juan Bautista Rodríguez', value2: '', value3: '' },
    { id: 439, value: 'Cuara', value2: '', value3: '' },
    { id: 440, value: 'Diego de Lozada', value2: '', value3: '' },
    { id: 441, value: 'Paraíso de San José', value2: '', value3: '' },
    { id: 442, value: 'Tintorero', value2: '', value3: '' },
    { id: 443, value: 'José Bernardo Dorante', value2: '', value3: '' },
    { id: 444, value: 'Coronel Mariano Peraza', value2: '', value3: '' },
    { id: 445, value: 'Anzoátegui', value2: '', value3: '' },
    { id: 446, value: 'Guárico', value2: '', value3: '' },
    { id: 447, value: 'Hilario Luna y Luna', value2: '', value3: '' },
    { id: 448, value: 'Humocaro Bajo', value2: '', value3: '' },
    { id: 449, value: 'Humocaro Alto', value2: '', value3: '' },
    { id: 450, value: 'La Candelaria', value2: '', value3: '' },
    { id: 451, value: 'Morán', value2: '', value3: '' },
    { id: 452, value: 'Cabudare', value2: '', value3: '' },
    { id: 453, value: 'José Gregorio Bastidas', value2: '', value3: '' },
    { id: 454, value: 'Agua Viva', value2: '', value3: '' },
    { id: 455, value: 'Buría', value2: '', value3: '' },
    { id: 456, value: 'Gustavo Vega', value2: '', value3: '' },
    { id: 457, value: 'Sarare', value2: '', value3: '' },
    { id: 458, value: 'Antonio Díaz', value2: '', value3: '' },
    { id: 459, value: 'Camacaro', value2: '', value3: '' },
    { id: 460, value: 'Castañeda', value2: '', value3: '' },
    { id: 461, value: 'Cecilio Zubillaga', value2: '', value3: '' },
    { id: 462, value: 'Chiquinquira', value2: '', value3: '' },
    { id: 463, value: 'El Blanco', value2: '', value3: '' },
    { id: 464, value: 'Espinoza de los Monteros', value2: '', value3: '' },
    { id: 465, value: 'Heriberto Arrollo', value2: '', value3: '' },
    { id: 466, value: 'Lara', value2: '', value3: '' },
    { id: 467, value: 'Manuel Morillo', value2: '', value3: '' },
    { id: 468, value: 'Montaña Verde', value2: '', value3: '' },
    { id: 469, value: 'Montes de Oca', value2: '', value3: '' },
    { id: 470, value: 'Reyes de Vargas', value2: '', value3: '' },
    { id: 471, value: 'Torres', value2: '', value3: '' },
    { id: 472, value: 'Trinidad Samuel', value2: '', value3: '' },
    { id: 473, value: 'Xaguas', value2: '', value3: '' },
    { id: 474, value: 'Siquisique', value2: '', value3: '' },
    { id: 475, value: 'Moroturo', value2: '', value3: '' },
    { id: 476, value: 'Presidente Betancourt', value2: '', value3: '' },
    { id: 477, value: 'Presidente Páez', value2: '', value3: '' },
    { id: 478, value: 'Presidente Rómulo Gallegos', value2: '', value3: '' },
    { id: 479, value: 'Gabriel Picón González', value2: '', value3: '' },
    { id: 480, value: 'Héctor Amable Mora', value2: '', value3: '' },
    { id: 481, value: 'José Nucete Sardi', value2: '', value3: '' },
    { id: 482, value: 'Pulido Méndez', value2: '', value3: '' },
    { id: 483, value: 'La Azulita', value2: '', value3: '' },
    { id: 484, value: 'Santa Cruz de Mora', value2: '', value3: '' },
    { id: 485, value: 'Mesa Bolívar', value2: '', value3: '' },
    { id: 486, value: 'Mesa de Las Palmas', value2: '', value3: '' },
    { id: 487, value: 'Aricagua', value2: '', value3: '' },
    { id: 488, value: 'Canagua', value2: '', value3: '' },
    { id: 489, value: 'Capurí', value2: '', value3: '' },
    { id: 490, value: 'Chacantá', value2: '', value3: '' },
    { id: 491, value: 'El Molino', value2: '', value3: '' },
    { id: 492, value: 'Guaimaral', value2: '', value3: '' },
    { id: 493, value: 'Mucutuy', value2: '', value3: '' },
    { id: 494, value: 'Mucuchachí', value2: '', value3: '' },
    { id: 495, value: 'Fernández Peña', value2: '', value3: '' },
    { id: 496, value: 'Matriz', value2: '', value3: '' },
    { id: 497, value: 'Acequias', value2: '', value3: '' },
    { id: 498, value: 'Jají', value2: '', value3: '' },
    { id: 499, value: 'La Mesa', value2: '', value3: '' },
    { id: 500, value: 'San José del Sur', value2: '', value3: '' },
    { id: 501, value: 'Tucaní', value2: '', value3: '' },
    { id: 502, value: 'Florencio Ramírez', value2: '', value3: '' },
    { id: 503, value: 'Santo Domingo', value2: '', value3: '' },
    { id: 504, value: 'Las Piedras', value2: '', value3: '' },
    { id: 505, value: 'Guaraque', value2: '', value3: '' },
    { id: 506, value: 'Mesa de Quintero', value2: '', value3: '' },
    { id: 507, value: 'Río Negro', value2: '', value3: '' },
    { id: 508, value: 'Arapuey', value2: '', value3: '' },
    { id: 509, value: 'Palmira', value2: '', value3: '' },
    { id: 510, value: 'San Cristóbal de Torondoy', value2: '', value3: '' },
    { id: 511, value: 'Torondoy', value2: '', value3: '' },
    { id: 512, value: 'Antonio Spinetti Dini', value2: '', value3: '' },
    { id: 513, value: 'Arias', value2: '', value3: '' },
    { id: 514, value: 'Caracciolo Parra Pérez', value2: '', value3: '' },
    { id: 515, value: 'Domingo Peña', value2: '', value3: '' },
    { id: 516, value: 'El Llano', value2: '', value3: '' },
    { id: 517, value: 'Gonzalo Picón Febres', value2: '', value3: '' },
    { id: 518, value: 'Jacinto Plaza', value2: '', value3: '' },
    { id: 519, value: 'Juan Rodríguez Suárez', value2: '', value3: '' },
    { id: 520, value: 'Lasso de la Vega', value2: '', value3: '' },
    { id: 521, value: 'Mariano Picón Salas', value2: '', value3: '' },
    { id: 522, value: 'Milla', value2: '', value3: '' },
    { id: 523, value: 'Osuna Rodríguez', value2: '', value3: '' },
    { id: 524, value: 'Sagrario', value2: '', value3: '' },
    { id: 525, value: 'Los Nevados', value2: '', value3: '' },
    { id: 526, value: 'La Venta', value2: '', value3: '' },
    { id: 527, value: 'Piñango', value2: '', value3: '' },
    { id: 528, value: 'Timotes', value2: '', value3: '' },
    { id: 529, value: 'Eloy Paredes', value2: '', value3: '' },
    { id: 530, value: 'San Rafael de Alcázar', value2: '', value3: '' },
    { id: 531, value: 'Santa Elena de Arenales', value2: '', value3: '' },
    { id: 532, value: 'Santa María de Caparo', value2: '', value3: '' },
    { id: 533, value: 'Pueblo Llano', value2: '', value3: '' },
    { id: 534, value: 'Cacute', value2: '', value3: '' },
    { id: 535, value: 'La Toma', value2: '', value3: '' },
    { id: 536, value: 'Mucuchíes', value2: '', value3: '' },
    { id: 537, value: 'Mucurubá', value2: '', value3: '' },
    { id: 538, value: 'Gerónimo Maldonado', value2: '', value3: '' },
    { id: 539, value: 'Bailadores', value2: '', value3: '' },
    { id: 540, value: 'Tabay', value2: '', value3: '' },
    { id: 541, value: 'Chiguará', value2: '', value3: '' },
    { id: 542, value: 'Estánques', value2: '', value3: '' },
    { id: 543, value: 'Lagunillas', value2: '', value3: '' },
    { id: 544, value: 'La Trampa', value2: '', value3: '' },
    { id: 545, value: 'Pueblo Nuevo del Sur', value2: '', value3: '' },
    { id: 546, value: 'María de la Concepción Palacios Blanco', value2: '', value3: '' },
    { id: 547, value: 'Nueva Bolivia', value2: '', value3: '' },
    { id: 548, value: 'Santa Apolonia', value2: '', value3: '' },
    { id: 549, value: 'Caño El Tigre', value2: '', value3: '' },
    { id: 550, value: 'Aragüita', value2: '', value3: '' },
    { id: 551, value: 'Arévalo González,', value2: '', value3: '' },
    { id: 552, value: 'Capaya', value2: '', value3: '' },
    { id: 553, value: 'Caucagua', value2: '', value3: '' },
    { id: 554, value: 'Panaquire', value2: '', value3: '' },
    { id: 555, value: 'Ribas', value2: '', value3: '' },
    { id: 556, value: 'El Café', value2: '', value3: '' },
    { id: 557, value: 'Marizapa', value2: '', value3: '' },
    { id: 558, value: 'Cumbo', value2: '', value3: '' },
    { id: 559, value: 'San José de Barlovento', value2: '', value3: '' },
    { id: 560, value: 'El Cafetal', value2: '', value3: '' },
    { id: 561, value: 'Las Minas', value2: '', value3: '' },
    { id: 562, value: 'Higuerote', value2: '', value3: '' },
    { id: 563, value: 'Curiepe', value2: '', value3: '' },
    { id: 564, value: 'Tacarigua de Brión', value2: '', value3: '' },
    { id: 565, value: 'Mamporal', value2: '', value3: '' },
    { id: 566, value: 'Carrizal', value2: '', value3: '' },
    { id: 567, value: 'Chacao', value2: '', value3: '' },
    { id: 568, value: 'Charallave', value2: '', value3: '' },
    { id: 569, value: 'Las Brisas', value2: '', value3: '' },
    { id: 570, value: 'Santa Rosalía de Palermo de El Hatillo', value2: '', value3: '' },
    { id: 571, value: 'Altagracia de la Montaña', value2: '', value3: '' },
    { id: 572, value: 'Cecilio Acosta', value2: '', value3: '' },
    { id: 573, value: 'Los Teques', value2: '', value3: '' },
    { id: 574, value: 'El Jarillo.', value2: '', value3: '' },
    { id: 575, value: 'San Pedro.', value2: '', value3: '' },
    { id: 576, value: 'Tácata.', value2: '', value3: '' },
    { id: 577, value: 'Paracotos.', value2: '', value3: '' },
    { id: 578, value: 'Cartanal', value2: '', value3: '' },
    { id: 579, value: 'Santa Teresa del Tuy', value2: '', value3: '' },
    { id: 580, value: 'La Democracia', value2: '', value3: '' },
    { id: 581, value: 'Ocumare del Tuy', value2: '', value3: '' },
    { id: 582, value: 'San Antonio de los Altos', value2: '', value3: '' },
    { id: 583, value: 'Río Chico', value2: '', value3: '' },
    { id: 584, value: 'El Guapo', value2: '', value3: '' },
    { id: 585, value: 'Tacarigua de la Laguna', value2: '', value3: '' },
    { id: 586, value: 'Paparo', value2: '', value3: '' },
    { id: 587, value: 'San Fernando del Guapo', value2: '', value3: '' },
    { id: 588, value: 'Santa Lucía del Tuy', value2: '', value3: '' },
    { id: 589, value: 'Cúpira', value2: '', value3: '' },
    { id: 590, value: 'Machurucuto', value2: '', value3: '' },
    { id: 591, value: 'Guarenas', value2: '', value3: '' },
    { id: 592, value: 'San Antonio de Yare', value2: '', value3: '' },
    { id: 593, value: 'San Francisco de Yare', value2: '', value3: '' },
    { id: 594, value: 'Leoncio Martínez', value2: '', value3: '' },
    { id: 595, value: 'Caucagüita', value2: '', value3: '' },
    { id: 596, value: 'Filas de Mariche', value2: '', value3: '' },
    { id: 597, value: 'La Dolorita', value2: '', value3: '' },
    { id: 598, value: 'Petare', value2: '', value3: '' },
    { id: 599, value: 'Cúa', value2: '', value3: '' },
    { id: 600, value: 'Nueva Cúa', value2: '', value3: '' },
    { id: 601, value: 'Guatire', value2: '', value3: '' },
    { id: 602, value: 'San Antonio de Maturín', value2: '', value3: '' },
    { id: 603, value: 'San Francisco de Maturín', value2: '', value3: '' },
    { id: 604, value: 'Aguasay', value2: '', value3: '' },
    { id: 605, value: 'Caripito', value2: '', value3: '' },
    { id: 606, value: 'El Guácharo', value2: '', value3: '' },
    { id: 607, value: 'La Guanota', value2: '', value3: '' },
    { id: 608, value: 'Sabana de Piedra', value2: '', value3: '' },
    { id: 609, value: 'Teresen', value2: '', value3: '' },
    { id: 610, value: 'Caripe', value2: '', value3: '' },
    { id: 611, value: 'Areo', value2: '', value3: '' },
    { id: 612, value: 'Capital Cedeño', value2: '', value3: '' },
    { id: 613, value: 'San Félix de Cantalicio', value2: '', value3: '' },
    { id: 614, value: 'Viento Fresco', value2: '', value3: '' },
    { id: 615, value: 'El Tejero', value2: '', value3: '' },
    { id: 616, value: 'Punta de Mata', value2: '', value3: '' },
    { id: 617, value: 'Las Alhuacas', value2: '', value3: '' },
    { id: 618, value: 'Tabasca', value2: '', value3: '' },
    { id: 619, value: 'Temblador', value2: '', value3: '' },
    { id: 620, value: 'Alto de los Godos', value2: '', value3: '' },
    { id: 621, value: 'Boquerón', value2: '', value3: '' },
    { id: 622, value: 'Las Cocuizas', value2: '', value3: '' },
    { id: 623, value: 'La Cruz', value2: '', value3: '' },
    { id: 624, value: 'San Simón', value2: '', value3: '' },
    { id: 625, value: 'El Corozo', value2: '', value3: '' },
    { id: 626, value: 'El Furrial', value2: '', value3: '' },
    { id: 627, value: 'Jusepín', value2: '', value3: '' },
    { id: 628, value: 'La Pica', value2: '', value3: '' },
    { id: 629, value: 'Aparicio', value2: '', value3: '' },
    { id: 630, value: 'Aragua de Maturín', value2: '', value3: '' },
    { id: 631, value: 'Chaguaramal', value2: '', value3: '' },
    { id: 632, value: 'El Pinto', value2: '', value3: '' },
    { id: 633, value: 'Guanaguana', value2: '', value3: '' },
    { id: 634, value: 'La Toscana', value2: '', value3: '' },
    { id: 635, value: 'Taguaya', value2: '', value3: '' },
    { id: 636, value: 'Quiriquire', value2: '', value3: '' },
    { id: 637, value: 'Los Barrancos de Fajardo', value2: '', value3: '' },
    { id: 638, value: 'Uracoa', value2: '', value3: '' },
    { id: 639, value: 'Antolín del Campo', value2: '', value3: '' },
    { id: 640, value: 'San Juan Bautista', value2: '', value3: '' },
    { id: 641, value: 'Zabala', value2: '', value3: '' },
    { id: 642, value: 'García', value2: '', value3: '' },
    { id: 643, value: 'Francisco Fajardo', value2: '', value3: '' },
    { id: 644, value: 'Guevara', value2: '', value3: '' },
    { id: 645, value: 'Cerro de Matasiete', value2: '', value3: '' },
    { id: 646, value: 'San Francisco de Macanao', value2: '', value3: '' },
    { id: 647, value: 'Boca de Río', value2: '', value3: '' },
    { id: 648, value: 'Aguirre', value2: '', value3: '' },
    { id: 649, value: 'Maneiro', value2: '', value3: '' },
    { id: 650, value: 'Adrián', value2: '', value3: '' },
    { id: 651, value: 'Juan Griego', value2: '', value3: '' },
    { id: 652, value: 'Mariño', value2: '', value3: '' },
    { id: 653, value: 'Tubores', value2: '', value3: '' },
    { id: 654, value: 'Los Barales', value2: '', value3: '' },
    { id: 655, value: 'Vicente Fuentes', value2: '', value3: '' },
    { id: 656, value: 'Villalba', value2: '', value3: '' },
    { id: 657, value: 'Agua Blanca', value2: '', value3: '' },
    { id: 658, value: 'Araure', value2: '', value3: '' },
    { id: 659, value: 'Río Acarigua', value2: '', value3: '' },
    { id: 660, value: 'Uveral', value2: '', value3: '' },
    { id: 661, value: 'Cordova', value2: '', value3: '' },
    { id: 662, value: 'Guanare', value2: '', value3: '' },
    { id: 663, value: 'San José de la Montaña', value2: '', value3: '' },
    { id: 664, value: 'San Juan de Guanaguanare', value2: '', value3: '' },
    { id: 665, value: 'Virgen de Coromoto', value2: '', value3: '' },
    { id: 666, value: 'Guanarito', value2: '', value3: '' },
    { id: 667, value: 'Trinidad de la Capilla', value2: '', value3: '' },
    { id: 668, value: 'Divina Pastora', value2: '', value3: '' },
    { id: 669, value: 'Chabasquén', value2: '', value3: '' },
    { id: 670, value: 'Peña Blanca', value2: '', value3: '' },
    { id: 671, value: 'Aparición', value2: '', value3: '' },
    { id: 672, value: 'La Estación', value2: '', value3: '' },
    { id: 673, value: 'Ospino', value2: '', value3: '' },
    { id: 674, value: 'Acarigua', value2: '', value3: '' },
    { id: 675, value: 'Payara', value2: '', value3: '' },
    { id: 676, value: 'Pimpinela', value2: '', value3: '' },
    { id: 677, value: 'Ramón Peraza', value2: '', value3: '' },
    { id: 678, value: 'Caño Delgadito', value2: '', value3: '' },
    { id: 679, value: 'Papelón', value2: '', value3: '' },
    { id: 680, value: 'Antolín Tovar Anquino', value2: '', value3: '' },
    { id: 681, value: 'Boconoíto', value2: '', value3: '' },
    { id: 682, value: 'Santa Fé', value2: '', value3: '' },
    { id: 683, value: 'San Rafael de Onoto', value2: '', value3: '' },
    { id: 684, value: 'Thelmo Morles', value2: '', value3: '' },
    { id: 685, value: 'Florida', value2: '', value3: '' },
    { id: 686, value: 'El Playón', value2: '', value3: '' },
    { id: 687, value: 'Biscucuy', value2: '', value3: '' },
    { id: 688, value: 'San José de Saguaz', value2: '', value3: '' },
    { id: 689, value: 'San Rafael de Palo Alzado', value2: '', value3: '' },
    { id: 690, value: 'Uvencio Antonio Velásquez', value2: '', value3: '' },
    { id: 691, value: 'Villa Bruzual', value2: '', value3: '' },
    { id: 692, value: 'Canelones', value2: '', value3: '' },
    { id: 693, value: 'San Isidro Labrador', value2: '', value3: '' },
    { id: 694, value: 'San José de Areocuar', value2: '', value3: '' },
    { id: 695, value: 'Tavera Acosta', value2: '', value3: '' },
    { id: 696, value: 'Río Caribe', value2: '', value3: '' },
    { id: 697, value: 'Antonio José de Sucre', value2: '', value3: '' },
    { id: 698, value: 'El Morro de Puerto Santo', value2: '', value3: '' },
    { id: 699, value: 'Puerto Santo', value2: '', value3: '' },
    { id: 700, value: 'San Juan de las Galdonas', value2: '', value3: '' },
    { id: 701, value: 'El Rincón', value2: '', value3: '' },
    { id: 702, value: 'General Francisco Antonio Vázquez', value2: '', value3: '' },
    { id: 703, value: 'Guaraúnos', value2: '', value3: '' },
    { id: 704, value: 'Tunapuicito', value2: '', value3: '' },
    { id: 705, value: 'Maracapana', value2: '', value3: '' },
    { id: 706, value: 'Marigüitar', value2: '', value3: '' },
    { id: 707, value: 'El Paujil', value2: '', value3: '' },
    { id: 708, value: 'Yaguaraparo', value2: '', value3: '' },
    { id: 709, value: 'Araya', value2: '', value3: '' },
    { id: 710, value: 'Chacopata', value2: '', value3: '' },
    { id: 711, value: 'Manicuare', value2: '', value3: '' },
    { id: 712, value: 'Tunapuy', value2: '', value3: '' },
    { id: 713, value: 'Campo Elías', value2: '', value3: '' },
    { id: 714, value: 'Irapa', value2: '', value3: '' },
    { id: 715, value: 'Campo Claro', value2: '', value3: '' },
    { id: 716, value: 'Marabal', value2: '', value3: '' },
    { id: 717, value: 'San Antonio de Irapa', value2: '', value3: '' },
    { id: 718, value: 'Soro', value2: '', value3: '' },
    { id: 719, value: 'San Antonio del Golfo', value2: '', value3: '' },
    { id: 720, value: 'Cumanacoa', value2: '', value3: '' },
    { id: 721, value: 'Arenas', value2: '', value3: '' },
    { id: 722, value: 'Cocollar', value2: '', value3: '' },
    { id: 723, value: 'San Lorenzo', value2: '', value3: '' },
    { id: 724, value: 'Cariaco', value2: '', value3: '' },
    { id: 725, value: 'Catuaro', value2: '', value3: '' },
    { id: 726, value: 'Rendón', value2: '', value3: '' },
    { id: 727, value: 'Santa María', value2: '', value3: '' },
    { id: 728, value: 'Altagracia Cumaná', value2: '', value3: '' },
    { id: 729, value: 'Santa Inés Cumaná', value2: '', value3: '' },
    { id: 730, value: 'Valentín Valiente Cumaná', value2: '', value3: '' },
    { id: 731, value: 'Ayacucho Cumaná', value2: '', value3: '' },
    { id: 732, value: 'Gran Mariscal', value2: '', value3: '' },
    { id: 733, value: 'Cristóbal Colón', value2: '', value3: '' },
    { id: 734, value: 'Bideau', value2: '', value3: '' },
    { id: 735, value: 'Punta de Piedras', value2: '', value3: '' },
    { id: 736, value: 'Güiria', value2: '', value3: '' },
    { id: 737, value: 'Cordero', value2: '', value3: '' },
    { id: 738, value: 'Las Mesas', value2: '', value3: '' },
    { id: 739, value: 'Rivas Berti', value2: '', value3: '' },
    { id: 740, value: 'San Juan de Colón', value2: '', value3: '' },
    { id: 741, value: 'San Pedro del Río', value2: '', value3: '' },
    { id: 742, value: 'Isaías Medina Angarita', value2: '', value3: '' },
    { id: 743, value: 'Juan Vicente Gómez', value2: '', value3: '' },
    { id: 744, value: 'Palotal', value2: '', value3: '' },
    { id: 745, value: 'San Antonio del Táchira', value2: '', value3: '' },
    { id: 746, value: 'Amenodoro Rangel Lamús', value2: '', value3: '' },
    { id: 747, value: 'La Florida', value2: '', value3: '' },
    { id: 748, value: 'Táriba', value2: '', value3: '' },
    { id: 749, value: 'Santa Ana del Táchira', value2: '', value3: '' },
    { id: 750, value: 'Alberto Adriani', value2: '', value3: '' },
    { id: 751, value: 'San Rafael del Piñal', value2: '', value3: '' },
    { id: 752, value: 'San José de Bolívar', value2: '', value3: '' },
    { id: 753, value: 'Boca de Grita', value2: '', value3: '' },
    { id: 754, value: 'La Fría', value2: '', value3: '' },
    { id: 755, value: 'Capacho Nuevo', value2: '', value3: '' },
    { id: 756, value: 'Juan Germán Roscio', value2: '', value3: '' },
    { id: 757, value: 'Román Cárdenas', value2: '', value3: '' },
    { id: 758, value: 'Emilio Constantino Guerrero', value2: '', value3: '' },
    { id: 759, value: 'La Grita', value2: '', value3: '' },
    { id: 760, value: 'Monseñor Miguel Antonio Salas', value2: '', value3: '' },
    { id: 761, value: 'El Cobre', value2: '', value3: '' },
    { id: 762, value: 'Bramón', value2: '', value3: '' },
    { id: 763, value: 'La Petrólea', value2: '', value3: '' },
    { id: 764, value: 'Quinimarí', value2: '', value3: '' },
    { id: 765, value: 'Rubio', value2: '', value3: '' },
    { id: 766, value: 'Capacho Viejo', value2: '', value3: '' },
    { id: 767, value: 'Cipriano Castro', value2: '', value3: '' },
    { id: 768, value: 'Manuel Felipe Rugeles', value2: '', value3: '' },
    { id: 769, value: 'Abejales', value2: '', value3: '' },
    { id: 770, value: 'Doradas', value2: '', value3: '' },
    { id: 771, value: 'Emeterio Ochoa', value2: '', value3: '' },
    { id: 772, value: 'San Joaquín de Navay', value2: '', value3: '' },
    { id: 773, value: 'Lobatera', value2: '', value3: '' },
    { id: 774, value: 'Constitución', value2: '', value3: '' },
    { id: 775, value: 'Michelena', value2: '', value3: '' },
    { id: 776, value: 'Coloncito', value2: '', value3: '' },
    { id: 777, value: 'La Palmita', value2: '', value3: '' },
    { id: 778, value: 'Ureña', value2: '', value3: '' },
    { id: 779, value: 'Nueva Arcadia', value2: '', value3: '' },
    { id: 780, value: 'Delicias', value2: '', value3: '' },
    { id: 781, value: 'Boconó', value2: '', value3: '' },
    { id: 782, value: 'Hernández', value2: '', value3: '' },
    { id: 783, value: 'La Tendida', value2: '', value3: '' },
    { id: 784, value: 'Francisco Romero Lobo', value2: '', value3: '' },
    { id: 785, value: 'La Concordia', value2: '', value3: '' },
    { id: 786, value: 'Pedro María Morantes', value2: '', value3: '' },
    { id: 787, value: 'Umuquena', value2: '', value3: '' },
    { id: 788, value: 'Seboruco', value2: '', value3: '' },
    { id: 789, value: 'Eleazar López Contreras', value2: '', value3: '' },
    { id: 790, value: 'Capital Sucre', value2: '', value3: '' },
    { id: 791, value: 'San Josecito', value2: '', value3: '' },
    { id: 792, value: 'Cárdenas', value2: '', value3: '' },
    { id: 793, value: 'Juan Pablo Peñaloza', value2: '', value3: '' },
    { id: 794, value: 'Potosí', value2: '', value3: '' },
    { id: 795, value: 'Pregonero', value2: '', value3: '' },
    { id: 796, value: 'Araguaney', value2: '', value3: '' },
    { id: 797, value: 'El Jaguito', value2: '', value3: '' },
    { id: 798, value: 'La Esperanza', value2: '', value3: '' },
    { id: 799, value: 'Santa Isabel', value2: '', value3: '' },
    { id: 800, value: 'El Carmen', value2: '', value3: '' },
    { id: 801, value: 'Mosquey', value2: '', value3: '' },
    { id: 802, value: 'Ayacucho', value2: '', value3: '' },
    { id: 803, value: 'Burbusay', value2: '', value3: '' },
    { id: 804, value: 'General Ribas', value2: '', value3: '' },
    { id: 805, value: 'Guaramacal', value2: '', value3: '' },
    { id: 806, value: 'Vega De Guaramacal', value2: '', value3: '' },
    { id: 807, value: 'Monseñor Jáuregui', value2: '', value3: '' },
    { id: 808, value: 'Rafael Rangel', value2: '', value3: '' },
    { id: 809, value: 'Sabana Grande', value2: '', value3: '' },
    { id: 810, value: 'Cheregüé', value2: '', value3: '' },
    { id: 811, value: 'Granados', value2: '', value3: '' },
    { id: 812, value: 'Arnoldo Gabaldón', value2: '', value3: '' },
    { id: 813, value: 'Bolivia', value2: '', value3: '' },
    { id: 814, value: 'Carrillo', value2: '', value3: '' },
    { id: 815, value: 'Cegarra', value2: '', value3: '' },
    { id: 816, value: 'Chejendé', value2: '', value3: '' },
    { id: 817, value: 'Manuel Salvador Ulloa', value2: '', value3: '' },
    { id: 818, value: 'Carache', value2: '', value3: '' },
    { id: 819, value: 'La Concepción', value2: '', value3: '' },
    { id: 820, value: 'Cuicas', value2: '', value3: '' },
    { id: 821, value: 'Panamericana', value2: '', value3: '' },
    { id: 822, value: 'Escuque', value2: '', value3: '' },
    { id: 823, value: 'Sabana Libre', value2: '', value3: '' },
    { id: 824, value: 'Los Caprichos', value2: '', value3: '' },
    { id: 825, value: 'El Progreso', value2: '', value3: '' },
    { id: 826, value: 'La Ceiba', value2: '', value3: '' },
    { id: 827, value: 'Tres De Febrero', value2: '', value3: '' },
    { id: 828, value: 'El Dividive', value2: '', value3: '' },
    { id: 829, value: 'Agua Santa', value2: '', value3: '' },
    { id: 830, value: 'Agua Caliente', value2: '', value3: '' },
    { id: 831, value: 'El Cenizo', value2: '', value3: '' },
    { id: 832, value: 'Valerita', value2: '', value3: '' },
    { id: 833, value: 'Monte Carmelo', value2: '', value3: '' },
    { id: 834, value: 'Santa María Del Horcón', value2: '', value3: '' },
    { id: 835, value: 'Motatán', value2: '', value3: '' },
    { id: 836, value: 'El Baño', value2: '', value3: '' },
    { id: 837, value: 'Jalisco', value2: '', value3: '' },
    { id: 838, value: 'Pampán', value2: '', value3: '' },
    { id: 839, value: 'Flor De Patria', value2: '', value3: '' },
    { id: 840, value: 'La Paz', value2: '', value3: '' },
    { id: 841, value: 'Pampanito', value2: '', value3: '' },
    { id: 842, value: 'Pampanito II', value2: '', value3: '' },
    { id: 843, value: 'Betijoque', value2: '', value3: '' },
    { id: 844, value: 'José Gregorio Hernández', value2: '', value3: '' },
    { id: 845, value: 'La Pueblita', value2: '', value3: '' },
    { id: 846, value: 'Los Cedros', value2: '', value3: '' },
    { id: 847, value: 'Carvajal', value2: '', value3: '' },
    { id: 848, value: 'Campo Alegre', value2: '', value3: '' },
    { id: 849, value: 'Antonio Nicolás Briceño', value2: '', value3: '' },
    { id: 850, value: 'José Leonardo Suárez', value2: '', value3: '' },
    { id: 851, value: 'Sabana De Mendoza', value2: '', value3: '' },
    { id: 852, value: 'Junín', value2: '', value3: '' },
    { id: 853, value: 'Valmore Rodríguez', value2: '', value3: '' },
    { id: 854, value: 'Andrés Linares', value2: '', value3: '' },
    { id: 855, value: 'Cristóbal Mendoza', value2: '', value3: '' },
    { id: 856, value: 'Cruz Carrillo', value2: '', value3: '' },
    { id: 857, value: 'Monseñor Carrillo', value2: '', value3: '' },
    { id: 858, value: 'Tres Esquinas', value2: '', value3: '' },
    { id: 859, value: 'Cabimbú', value2: '', value3: '' },
    { id: 860, value: 'Jajó', value2: '', value3: '' },
    { id: 861, value: 'La Mesa De Esnujaque', value2: '', value3: '' },
    { id: 862, value: 'Santiago', value2: '', value3: '' },
    { id: 863, value: 'Tuñame', value2: '', value3: '' },
    { id: 864, value: 'La Quebrada', value2: '', value3: '' },
    { id: 865, value: 'Juan Ignacio Montilla', value2: '', value3: '' },
    { id: 866, value: 'La Beatriz', value2: '', value3: '' },
    { id: 867, value: 'La Puerta', value2: '', value3: '' },
    { id: 868, value: 'Mendoza Del Valle De Momboy', value2: '', value3: '' },
    { id: 869, value: 'Mercedes Díaz', value2: '', value3: '' },
    { id: 870, value: 'Caraballeda', value2: '', value3: '' },
    { id: 871, value: 'Carayaca', value2: '', value3: '' },
    { id: 872, value: 'Carlos Soublette', value2: '', value3: '' },
    { id: 873, value: 'Caruao', value2: '', value3: '' },
    { id: 874, value: 'Catia La Mar', value2: '', value3: '' },
    { id: 875, value: 'El Junko', value2: '', value3: '' },
    { id: 876, value: 'La Guaira', value2: '', value3: '' },
    { id: 877, value: 'Macuto', value2: '', value3: '' },
    { id: 878, value: 'Maiquetía', value2: '', value3: '' },
    { id: 879, value: 'Naiguatá', value2: '', value3: '' },
    { id: 880, value: 'Urimare', value2: '', value3: '' },
    { id: 881, value: 'Arístides Bastidas', value2: '', value3: '' },
    { id: 882, value: 'Chivacoa', value2: '', value3: '' },
    { id: 883, value: 'Cocorote', value2: '', value3: '' },
    { id: 884, value: 'El Guayabo', value2: '', value3: '' },
    { id: 885, value: 'Farriar', value2: '', value3: '' },
    { id: 886, value: 'Manuel Monge', value2: '', value3: '' },
    { id: 887, value: 'Temerla', value2: '', value3: '' },
    { id: 888, value: 'Nirgua', value2: '', value3: '' },
    { id: 889, value: 'San Andrés', value2: '', value3: '' },
    { id: 890, value: 'Yaritagua', value2: '', value3: '' },
    { id: 891, value: 'San Javier', value2: '', value3: '' },
    { id: 892, value: 'Albarico', value2: '', value3: '' },
    { id: 893, value: 'San Felipe', value2: '', value3: '' },
    { id: 894, value: 'Urachiche', value2: '', value3: '' },
    { id: 895, value: 'Isla De Toas', value2: '', value3: '' },
    { id: 896, value: 'Monagas', value2: '', value3: '' },
    { id: 897, value: 'San Timoteo', value2: '', value3: '' },
    { id: 898, value: 'General Urdaneta', value2: '', value3: '' },
    { id: 899, value: 'Marcelino Briceño', value2: '', value3: '' },
    { id: 900, value: 'Nuevo', value2: '', value3: '' },
    { id: 901, value: 'Manuel Guanipa Matos', value2: '', value3: '' },
    { id: 902, value: 'Ambrosio', value2: '', value3: '' },
    { id: 903, value: 'Carmen Herrera', value2: '', value3: '' },
    { id: 904, value: 'La Rosa', value2: '', value3: '' },
    { id: 905, value: 'Germán Ríos Linares', value2: '', value3: '' },
    { id: 906, value: 'San Benito', value2: '', value3: '' },
    { id: 907, value: 'Rómulo Betancourt', value2: '', value3: '' },
    { id: 908, value: 'Jorge Hernández', value2: '', value3: '' },
    { id: 909, value: 'Punta Gorda', value2: '', value3: '' },
    { id: 910, value: 'Arístides Calvani', value2: '', value3: '' },
    { id: 911, value: 'Encontrados', value2: '', value3: '' },
    { id: 912, value: 'Udón Pérez', value2: '', value3: '' },
    { id: 913, value: 'Moralito', value2: '', value3: '' },
    { id: 914, value: 'Capital San Carlos Del Zulia', value2: '', value3: '' },
    { id: 915, value: 'Santa Cruz Del Zulia', value2: '', value3: '' },
    { id: 916, value: 'Urribarrí', value2: '', value3: '' },
    { id: 917, value: 'Carlos Quevedo', value2: '', value3: '' },
    { id: 918, value: 'Francisco Javier Pulgar', value2: '', value3: '' },
    { id: 919, value: 'Guamo-Gavilanes', value2: '', value3: '' },
    { id: 920, value: 'Mariano Parra León', value2: '', value3: '' },
    { id: 921, value: 'José Ramón Yépez', value2: '', value3: '' },
    { id: 922, value: 'Jesús María Semprún', value2: '', value3: '' },
    { id: 923, value: 'Barí', value2: '', value3: '' },
    { id: 924, value: 'El Carmelo', value2: '', value3: '' },
    { id: 925, value: 'Potreritos', value2: '', value3: '' },
    { id: 926, value: 'Alonso De Ojeda', value2: '', value3: '' },
    { id: 927, value: 'Venezuela', value2: '', value3: '' },
    { id: 928, value: 'Campo Lara', value2: '', value3: '' },
    { id: 929, value: 'Bartolomé De Las Casas', value2: '', value3: '' },
    { id: 930, value: 'San José De Perijá', value2: '', value3: '' },
    { id: 931, value: 'La Sierrita', value2: '', value3: '' },
    { id: 932, value: 'Las Parcelas', value2: '', value3: '' },
    { id: 933, value: 'Luis De Vicente', value2: '', value3: '' },
    { id: 934, value: 'Monseñor Marcos Sergio Godoy', value2: '', value3: '' },
    { id: 935, value: 'Ricaurte', value2: '', value3: '' },
    { id: 936, value: 'Tamare', value2: '', value3: '' },
    { id: 937, value: 'Antonio Borjas Romero', value2: '', value3: '' },
    { id: 938, value: 'Cacique Mara', value2: '', value3: '' },
    { id: 939, value: 'Carracciolo Parra Pérez', value2: '', value3: '' },
    { id: 940, value: 'Cristo De Aranza', value2: '', value3: '' },
    { id: 941, value: 'Coquivacoa', value2: '', value3: '' },
    { id: 942, value: 'Francisco Eugenio Bustamante', value2: '', value3: '' },
    { id: 943, value: 'Idelfonzo Vásquez', value2: '', value3: '' },
    { id: 944, value: 'Juana De Ávila', value2: '', value3: '' },
    { id: 945, value: 'Luis Hurtado Higuera', value2: '', value3: '' },
    { id: 946, value: 'Manuel Dagnino', value2: '', value3: '' },
    { id: 947, value: 'Olegario Villalobos', value2: '', value3: '' },
    { id: 948, value: 'Santa Lucía', value2: '', value3: '' },
    { id: 949, value: 'Venancio Pulgar', value2: '', value3: '' },
    { id: 950, value: 'Faría', value2: '', value3: '' },
    { id: 951, value: 'Ana María Campos', value2: '', value3: '' },
    { id: 952, value: 'Sinamaica', value2: '', value3: '' },
    { id: 953, value: 'Alta Guajira', value2: '', value3: '' },
    { id: 954, value: 'Elías Sánchez Rubio', value2: '', value3: '' },
    { id: 955, value: 'Guajira', value2: '', value3: '' },
    { id: 956, value: 'Donaldo García', value2: '', value3: '' },
    { id: 957, value: 'El Rosario', value2: '', value3: '' },
    { id: 958, value: 'Sixto Zambrano', value2: '', value3: '' },
    { id: 959, value: 'El Bajo', value2: '', value3: '' },
    { id: 960, value: 'Domitila Flores', value2: '', value3: '' },
    { id: 961, value: 'Francisco Ochoa', value2: '', value3: '' },
    { id: 962, value: 'Los Cortijos', value2: '', value3: '' },
    { id: 963, value: 'Marcial Hernández', value2: '', value3: '' },
    { id: 964, value: 'José Domingo Rus', value2: '', value3: '' },
    { id: 965, value: 'El Mene', value2: '', value3: '' },
    { id: 966, value: 'Pedro Lucas Urribarrí', value2: '', value3: '' },
    { id: 967, value: 'José Cenobio Urribarrí', value2: '', value3: '' },
    { id: 968, value: 'Rafael Maria Baralt', value2: '', value3: '' },
    { id: 969, value: 'Rafael Urdaneta', value2: '', value3: '' },
    { id: 970, value: 'Bobures', value2: '', value3: '' },
    { id: 971, value: 'Gibraltar', value2: '', value3: '' },
    { id: 972, value: 'Heras', value2: '', value3: '' },
    { id: 973, value: 'Monseñor Arturo Álvarez', value2: '', value3: '' },
    { id: 974, value: 'El Batey', value2: '', value3: '' },
    { id: 975, value: 'La Victoria', value2: '', value3: '' },
    { id: 976, value: 'Raúl Cuenca', value2: '', value3: '' }
];